### ISSUE TITLE
Fill missing docstring

### ISSUE THREAD

**Issue by eleurent** [eleurent/highway-env#10]

**Comment by abc283646346** [comment]
I'm a student who is interested in your project. But I don't know how to use this project with the usage. Is there a simple demo suitable for me to study? Thank you very much!

**Comment by eleurent** [comment]
Hi @abc283646346, this project is only focused on the simulation of a vehicle driving in several scenes.
The snippet in the usage tells you how to run the simulator, but it misses the code for controlling the vehicle. If you just want to run it with random behaviour, you can run:

```
import higwhay_env

env = gym.make("highway-v0")

done = False
while not done:
    action = env.action_space.sample()
    obs, reward, done, _ = env.step(action)
    env.render()
```

If, however, you want to see agents solving the task, you need to install https://github.com/eleurent/rl-agents
Then, you can run experiments by using the rl-agents/scripts/experiments.py script. For instance, to train a DQN:
python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/Agents/DQNAgent/baseline.json --test --episodes=10000

Does that help?

**Comment by abc283646346** [comment]
> Hi @abc283646346, this project is only focused on the simulation of a vehicle driving in several scenes.
> The snippet in the usage tells you how to run the simulator, but it misses the code for controlling the vehicle. If you just want to run it with random behaviour, you can run:
> 
> ```
> import higwhay_env
> 
> env = gym.make("highway-v0")
> 
> done = False
> while not done:
>     action = env.action_space.sample()
>     obs, reward, done, _ = env.step(action)
>     env.render()
> ```
> 
> If, however, you want to see agents solving the task, you need to install https://github.com/eleurent/rl-agents
> Then, you can run experiments by using the rl-agents/scripts/experiments.py script. For instance, to train a DQN:
> python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/Agents/DQNAgent/baseline.json --test --episodes=10000
> 
> Does that help?

Thank you very much! It helps me a lot! With your random behaviour's demo code, the project can run in a right way. But two more problems happened. 
One is the problem with "env = gym.make("highway-parking-v0")" , it shows that "AssertionError: Cannot call env.step() before calling reset()"?
The other one is when I run “python experiments.py”  with Python 2.7 or Python 3.6, it shows that "ModuleNotFoundError: No module named 'rl_agents.agents.dynamic_programming'"?
Do you know what's wrong with them? 
To train a DQN, is that I input the code "python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/Agents/DQNAgent/baseline.json --test --episodes=10000" into the terminal?
Thank you again!  Maybe my problems are in a low level, because I am a new guy in this field.

**Comment by eleurent** [comment]
Oh yes, right, you should probably call env.reset() before the while loop. This is a requirement of goal environments (GoalEnv).

The problem you get when running python experiments.py is that Python does not know where to find the rl_agents module. It should work if you installed it with pip, though.
Otherwise, you can try the following:
`PYTHONPATH=/path/to/rl-agents/ python experiments.py --<arguments>`
Oh, and the project only supports python3, by the way.
