### ISSUE TITLE
GPU has very low utilization during training.

### ISSUE THREAD

**Issue by dx2919717227** [eleurent/highway-env#103]
hello:
device: jetson nano and PC
tensorflow-version: tensorflow1.15.2 and tensorflow-gpu 1.15.2
env: highway-v0
  when i training a model use "highway-v0" and stable-baselines, CPU utilization reaches 100%,but GPU is very low.The same situation occurred when I trained the model on the PC.I use the "stable-baselines" official example and everything is normal. i want to know why.
 thanks for your any reply.

**Comment by eleurent** [comment]
Hi @dx2919717227,
The GPU utilization is probably low because the env simulation in CPU is actually the computational bottleneck, which is quite common in RL, but all the more with this environment which is implemented in python and not very well optimized.
This can be mitigated by using distributed training algorithms, where several workers are used to gather experiences on many CPU cores (stable-baselines should support it).
For the highway-v0 env in particular, you may want to decrease the number of agents in the scene, which should help a lot with performance.

**Comment by dx2919717227** [comment]
thanks a lot~
