### ISSUE TITLE
get the action and history of all cars

### ISSUE THREAD

**Issue by kargarisaac** [eleurent/highway-env#104]
Hi,

I'm trying to get the history of all cars and their action in each time-step. For the history when I set the label to True, it shows the id of each car but when I check the history of each car, I see that the id is different. I don't know what is going on here. Why ids are different for the history of one car but in the rendering, it is constant. 

It will also be great if there is any figure for the coordination of the scene. For example for intersection and roundabout. The x-y coordinate diagram.

Thank you

**Comment by eleurent** [comment]
Hi Isaac,

> I'm trying to get the history of all cars and their action in each time-step. For the history when I set the label to True, it shows the id of each car but when I check the history of each car, I see that the id is different. I don't know what is going on here. Why ids are different for the history of one car but in the rendering, it is constant.

To enable the storage the past history of all cars, you must configure the environment with
```python
env.config["show_trajectories"] = True
env.reset()
```
Then, the history of a `vehicle` in `env.road.vehicles` can be accessed through its field `vehicle.history`.
This history is described as a list of `Vehicle` instances, which is filled in by calling `vehicle.history.append(copy.deepcopy(vehicle))`
I decided to do this (using the Vehicle class as a containter rather then, say, directly storing the position/velocity) so that all other properties would be saved (e.g. the target speed, the color) and also in order to be able to use methods that already accept Vehicle instances, e.g. for rendering.
But then of course, since the vehicle object is duplicated, the saved copies have different ids (if you are referring to python's `id()` method, which is unique for each object). Is that troubling for you?

> It will also be great if there is any figure for the coordination of the scene. For example for intersection and roundabout. The x-y coordinate diagram.

I am not sure what you mean by x-y coordinate diagram or figure for the coordination. Could you give a little more details on what you need? Is the `show_trajectories` option not sufficient to display how vehicles coordinate?

**Comment by kargarisaac** [comment]
Thank you for your answer,

> Is that troubling for you?

No it's ok. I was thinking that maybe sth is wrong. I had to check the code more carefully. 

> I am not sure what you mean by x-y coordinate diagram or figure for the coordination. Could you give a little more details on what you need? Is the `show_trajectories` option not sufficient to display how vehicles coordinate?

For example for the intersection env, the coordinate system is as follows, I think:
```
-------------->x
|
|
y
```

The origin of x-y coordinate system for example. And also the same information for other environments too.

Thank you.

**Comment by eleurent** [comment]
The coordinates system is always in this convention (x axis is left-to-right and y is top-to-bottom), so the only information required is the location of the origin.
In parking/intersection/roundabout, it is located in the middle of the scene. 
In highway/merge, it is located at the top-left.
I could add this information to the documentation.

**Comment by kargarisaac** [comment]
> The coordinates system is always in this convention (x axis is left-to-right and y is top-to-bottom), so the only information required is the location of the origin.
> In parking/intersection/roundabout, it is located in the middle of the scene.
> In highway/merge, it is located at the top-left.
> I could add this information to the documentation.

Thank you. I think it's enough.
