### ISSUE TITLE
BicycleVehicle

### ISSUE THREAD

**Issue by BBDrive** [eleurent/highway-env#106]
If I set the dynamical of ContinuousAction to True, that is, simulate dynamics rather than kinematics, can the vehicle move with a changing longitudinal speed?

**Comment by BBDrive** [comment]
Looking forward to your answer. Thanks.

**Comment by eleurent** [comment]
Hi @BBDrive ,
I am not sure I understand the question: with both a kinematics and a dynamics model, the longitudinal speed of the vehicle changes according to the continuous `acceleration` control.

The differences between the two are:
- In the kinematics model, it is assumed that there is no sliding: when the vehicle *turns* the longitudinal velocity is preserved (but can still be changed with the acceleration control)
- In the dynamics model, the tire friction and sliding are simulated: 
  - the "acceleration" control now corresponds to a force rather than a acceleration per-se, i.e. if there is no friction (e.g. on an icy road) the vehicle will not accelerate
  - when the vehicle turns, a part of its longitudinal velocity will be converted to lateral velocity.

Does that answer your question?

**Comment by BBDrive** [comment]
Thank you for your answer.
In the script I saw that the dynamics model has two assumptions.
1. the vehicle is moving with a constant longitudinal speed
2. the steering input to front tires and the corresponding slip angles are small
If I control `acceleration` to change the longitudinal speed of the vehicle, will it break the above the first assumption?

**Comment by eleurent** [comment]
Aaaah I see, sorry about that, this comment is misplaced: these two assumptions are actually only required for the linearized version of the lateral dynamics, and this approximation is only done in some submethods of the class which are not used by default.

If you just use continuous actions, you will get the non-linear version of the dynamics which does not rely on any assumption of constant speed of small angles.

I'll fix the comments, thanks for the feedback

**Comment by BBDrive** [comment]
I have another question.
I set `duration=1000`, and I found that the sampling speed is very slow even if I did not set `env.render()`.
Is the sampling speed of setting `render` as `True` or `False` the same? Unlike the environment on the gym, setting `render=True` will be much faster.

**Comment by eleurent** [comment]
It should definitely be faster without rendering. I am not sure where you are setting `render=False`, though?

If the speed is too slow even without rendering, you could try decreasing the number of vehicles in the scene.
But for a 1000s episode, we would need a mechanism that dynamically spawns new vehicles in front of the ego vehicle and destroys those that are too far, in order to keep the number of simulated entities small enough while also allowing long episode duration.

**Comment by BBDrive** [comment]
I said `render=False` refers to not using `env.render()`, because this is expressed in gym. Ha-ha.
Thank you for your answer.

**Comment by BBDrive** [comment]
Hi.
If I want to change the friction of the ground in the dynamics model, do I only need to change the value of `FRICTION_FRONT` and `FRICTION_REAR`? The formula for friction is `f=umg`, so is the value `15.0` you defined in the script is `ug`?
Looking forward to your answer.

**Comment by eleurent** [comment]
Yes, I think so. 
And the (unrealistic) value of 1.0kg used for the mass doesn't really matter, since it gets simplified in the end (acceleration = force / mass). This way, the friction coefficient is "normalized".
