### ISSUE TITLE
Reward in highway-env with continuous control

### ISSUE THREAD

**Issue by ma-rapp** [eleurent/highway-env#109]
I am experimenting with continuous control in the highway-env. The reward is defined as

collision + right-lane + high-speed

The high-speed reward maps linearly from `0` at 20 m/s to `1` at 30 m/s and saturates both for lower and higher speeds. I understand that this comes from the `MDPVehicle` that only selects a speed between 20 and 30 m/s. However, continuous control allows speeds between -40 m/s and +40 m/s.

I find it unintuitive that no matter whether the agent goes reverse or at 20 m/s, it gets a reward of 0, and higher speeds than 30 m/s are not rewarded. I would find it much more intuitive if rewards are mapped linearly between 0 for 0 m/s and 1 for 40 m/s.

@eleurent: I would like to hear your opinion. Maybe you have an alternative view? Maybe you have an idea how to consistently change the reward definition without requiring the environment to know the agent class?

**Comment by eleurent** [comment]
Yes, this definition of the reward was initially suited for a discrete action space that maintains the velocity in [20, 30] m/s, but I agree that it should be normalized for the range of velocities that you expect your agent to go through.

I guess the most flexible solution is to add a `reward_speed_map = [a, b]` config parameter such that the corresponding reward is `clip(a*s+b, -1, 1)`, so that users can tune it according to their needs.

**Comment by ma-rapp** [comment]
Thanks for the very fast reply :+1: 

Your idea sounds great. I will implement it right away...

**Comment by ma-rapp** [comment]
I implemented a slightly different variant. Instead of configuring parameters of a linear equation, the user can configure the min. and max. velocity that is considered for the reward calculation:

    clip(lmap(speed, config["reward_speed_range"], [0, 1]), 0, 1)

Examples:
discrete action space: `"reward_speed_range": [20, 30]`
continuous action space: `"reward_speed_range": [0, 40]`

**Comment by eleurent** [comment]
Even better, thanks!
