### ISSUE TITLE
Setting initial position of controlled vehicles

### ISSUE THREAD

**Issue by parvkpr** [eleurent/highway-env#111]
I am trying to create an environment in which I want 2 controlled vehicles and zero other vehicles (This is a pretty common use case in formal systems called Adaptive Cruise Control). My use case needs them to be in the same lane. Unfortunately, when I tried to set the number of lanes to 1 it gives me a divide by zero error (stemming from reward calculation I assume).  The least number of lanes that work with the environment are 2. I notice that sometimes they'd spawn in the same lane and sometime they'd spawn in different lanes and I wanna constrain them to spawn in the same lane. Also slightly unrelated but the observation vector for the other car becomes 0 valued once my main ego car overtakes it. Is this an inherent feature of the env?

**Comment by eleurent** [comment]
Hi @parvkpr,

> Unfortunately, when I tried to set the number of lanes to 1 it gives me a divide by zero error (stemming from reward calculation I assume)

Okay, we have to fix that, thanks for the feedback.

> I wanna constrain them to spawn in the same lane

I propose to add an environment config `controlled_vehicles_lane`, with None as a default value, which means random (as of now). If an integer value is used instead, the controlled vehicles will all spawn on the corresponding lane.

> Also slightly unrelated but the observation vector for the other car becomes 0 valued once my main ego car overtakes it. Is this an inherent feature of the env?

By default yes, so that the driving policy focuses on vehicles ahead only. But you can turn this off by setting `see_behind=True` in the observation configuration.
