### ISSUE TITLE
meaning of lane_index

### ISSUE THREAD

**Issue by SHITIANYU-hue** [eleurent/highway-env#112]
In the kinematics.py you wrote **lane_index: index of the lane where the vehicle is located** 
In the tutorial, it says:
LaneIndex is a tuple containing:
a string identifier of a starting position
a string identifier of an ending position
an integer giving the index of the described lane, in the (unique) road from the starting to the ending position

But I don't quite understand what is the meaning of staring and ending position? why it is a string rather than an integer? 

For example, in highway env, I set the lane index as _lane_index=("0","1",0)_  it can run successfully, but I don't quite understand why we only can set it as 0 and 1?
![image](https://user-images.githubusercontent.com/38762389/95154022-dc57e480-075e-11eb-8e3d-42a68a170055.png)

Thanks and look forward to your reply!

**Comment by eleurent** [comment]
Hi @SHITIANYU-hue,

This comes from how we describe the topology of the road network. Each road section has a geometry described by a list of Lane objects (one per lane), but it is also referenced by giving a symbolic name (a string) to its starting and end positions, e.g. "A" and "B". This way, we can describe how different road segments are connected to each other, e.g. one from "A" to "B", another from "B" to "C", so that vehicles can plan a route "A->B->C" through the network, represented as a graph.

Thus, to reference of Lane (geometry) object, you must provide a tuple (LaneIndex) containing
* the start & end identifiers (str) of the road section
* the index (int) of the lane in this road section

In highway-env, there is only a single road segment, and the start and end positions of the road are represented by the strings "0" and "1", which I agree is not very informative and should probably be changed.

**Comment by SHITIANYU-hue** [comment]
Thanks for your reply! What I am trying to do is making the vehicle start from position A(e.g. 5m) in lane 1 and **end in position B(e.g. 100m) in lane 2**. I have seen that there are several initialization methods for vehicles in the kinematics.py. But it seems that we cannot set the end position.

**Comment by eleurent** [comment]
Do you mean a destination ?
The lane tracked by the ego-vehicle is controlled directly by the agent, through the lane-change actions, so it cannot really be set in advance.

And the desired lane is specified in the reward function, which for now favours driving on the rightmost lane. But you can change this by editing the reward function.

**Comment by SHITIANYU-hue** [comment]
Yes, a destination! Thanks, I will try to edit the reward function!

**Comment by eleurent** [comment]
Indeed, this variable was used to penalize lane change actions, but it is not used anymore.
I should either remove the variable or implement the penalty again.

If you want to use it, you can add LANE_CHANGE_REWARD to the reward if the action is 0 or 2 (for discrete actions).

**Comment by SHITIANYU-hue** [comment]
Thanks!
