### ISSUE TITLE
Bug on low vehicles_density values

### ISSUE THREAD

**Issue by BehradToghi** [eleurent/highway-env#115]
First of all thanks for the incredible work! Your environment has significantly helped our research.

I have noticed when I set the `'vehicles_density'` to a very low value (let's say `'vehicles_density' = 1/10 , 'vehicles_count': 150`, this causes a possible bug (I'm not sure). Seems like cars that are too far that they don't fit on the road stretch, somehow show up on the other side of the road (like a circular road). In the attached screenshot you can see although the two vehicles are close enough to Ego and within the `PERCEPTION_DISTANCE`, they do not  show up on the observation (printed in the console). 

Please let me know if the mistake is from my side.

![Screenshot from 2020-10-15 17-52-35](https://user-images.githubusercontent.com/25098045/96189841-3ef37200-0f0f-11eb-98fa-acf928aa6f01.png)

**Comment by eleurent** [comment]
Hi @BehradToghi,
Thanks for the feedback !

I could reproduce your issue, and it seems that indeed there is a weird bug, although it is not related to observations but rather to rendering. As you said, when vehicles are very far they still show up on the screen, and that is because of some wrapping effect that occurs when rendering a rectangle offscreen. Thus, it only happens on the rendered frame and not in the actual simulation (ie observation, collisions, etc): your observation was correct, but these vehicles that you see are spurious, not really there.

I will add a fix to prevent drawing a vehicle offscreen, which will fix this bug *and* improve rendering performances (I'm ashamed this wasn't implemented in the first place)

**Comment by BehradToghi** [comment]
Thanks for your response @eleurent . I was thinking it might be beneficial if we actually wrap the highway. Meaning if a `vehicle` runs out of the road stretch, it should show up on the other side of the road with updated coordinates, this way the density and the total number of the cars on the road stays constant. Additionally, one might suggest handling the discontinuity in the `x` direction at the very beginning and the end of the road through wrapping the geometry and making it circular.
At the end of the day, these are just design choices but I wanted to share my opinion with you.

**Comment by eleurent** [comment]
I agree, wrapping vehicles to maintain density is an interesting feature that should be added!
If discontinuities in the position are to be avoided, the [CircularLane](https://github.com/eleurent/highway-env/blob/master/highway_env/road/lane.py#L204) geometry can already be used, instead of StraightLane.
I wonder if it should be a configuration of the highway environment, or a separate environment.
