### ISSUE TITLE
ego distance to front vehicle?

### ISSUE THREAD

**Issue by Bernicorn** [eleurent/highway-env#133]
Hi,
in my trainings with ddqn on default highway_env, i noticed that the ego is doing really aggressive actions, like cut ins and crazy manuever. With lower vehicle_density the ego is doing rly soft manuever, and with higher density it become like i said, more aggressiv. I think that the highspeed_reward force the ego to do this agressive manuevers.
Is there any behavior model implemented, that controls the ego´s distance to it´s front vehicle, like the adjacent vehicle with the IDM and MOBIL? I already had a look to the code, but i couldn´t find any implementation like that...
If there is no implementation, does it make any sense to add it somehow to the reward function?
My idea to do it like the implementation of the highspeed reward:

distance_reward = 0.3

scaled_distance = utils.lmap(vehicle_distance, distance_range, [0.1, 1])
reward = distance_reward * scaled_distance

With higher distances the distance_reward will have stronger weightings.

thank you in advance

**Comment by eleurent** [comment]
> Is there any behavior model implemented, that controls the ego´s distance to it´s front vehicle, like the adjacent vehicle with the IDM and MOBIL? 

For the moment, the longitudinal and lateral behavioral models (like IDM and MOBIL) are mostly used for other vehicles, not for the controlled ego-vehicle. 
But it is true that it could be useful to have them also for the ego-vehicle (for instance, the agent could focus only on lateral control while the speed would be controlled by IDM, or the other way round)

> If there is no implementation, does it make any sense to add it somehow to the reward function?

It certainly makes sense, if you want the vehicle to be more cautious, to include additional terms in the reward function that better specify its intended behavior, e.g. by penalizing proximity to other vehicles as you suggested. And this is actually a very common thing to do, that I've seen in many papers. To that end, you can edit the environment's `_reward()` function as you like.

But I wanted to have a reward function as simple as possible: the collision penalty should in principle be sufficient for the agent to understand that near-collisions states should be avoided as well (because they lead to potential collisions, and thus a decreased expected reward) and develop a notion of safety distance, which should *emerge* in the value function, rather than being explicitly enforced by additional rewards.

Of course, in practice it is probably better and easier for the agent to provide a dense and informative feedback, but it leads to the pitfall of reward engineering and the need of tuning the weights of many factors to obtain the desired optimal policy.

**Comment by Mikael-OLS** [comment]
As you guys have written, it would be useful for me to use the MOBIL for a controlled ego-vehicle. Is there i quick and easy way to implement that?

**Comment by Bernicorn** [comment]
Thanks alot for the support @eleurent. I´ll give it a try and use the longitudinal part of the IDM class, like acceleration, desired gap and maximum speed in the controller of the ego vehicle.
@Mikael-OLS have you tried it yet?

**Comment by Bernicorn** [comment]
@Mikael-OLS it worked for me. The ego is now acting in the longitudinal way like an adjacent vehicle. I just added the IDM- behavior to the controller adjusted it to the ego vehicle and thats it.

**Comment by eleurent** [comment]
@Bernicorn thanks, can you share your addition through a pull request?

**Comment by SeasonedLeo** [comment]
@Bernicorn  I am trying to implement similar stuff , using IDM and MOBIL to use for EGO vehicle. The goal is to collect some data with this policy for offline RL . 

Could you please point me to the mplementation ?
