### ISSUE TITLE
problem about env configuration

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#138]
Hello! I want to apply continuous action in highway env, and set the env like this:
```
env_config={
...
"action": {                           
        "type": "ContinuousAction",
        "acceleration_range": [-5, 5.0],  
        "steering_range": [-np.pi / 4, np.pi / 4], 
        "longitudinal": True,             
        "lateral": True
    },
...
}
env = gym.make(env_config['id'])
env.unwrapped.configure(env_config)
env = wrappers.Monitor(env, log_path, video_callable=(None if env_config["display_record"] else False))
env.reset()
```
and I set the below code after env configuration
```
state_shape = env.observation_space.shape or env.observation_space.n
action_shape = env.action_space.shape or env.action_space.n
max_action = env.action_space.high[0]
```
but it warns that `'Discrete' object has no attribute 'high'`, I think it means that the content of `env_config` is not applied in highway env, for in the default config of highway env, the type of action is DiscreteMetaAction, but when I change the number of lanes in `env_config`,  video shows that lane number has been changed, only the config of action is not applied, that's weird

**Comment by eleurent** [comment]
Hello @Exasor 
The issue is the following:
1. the environment is created with the default configuration, i.e. a discrete action space
2. you configure it to use a continuous action space instead. However, this configuration is merely saved and will only be applied when env.reset() is called.
3. you wrap the environment into a monitor, which copies its current action space (i.e. spaces.Discrete)
4. then you reset the environment, the new configuration is applied, and the action space is changed to spaces.Box. However, the Monitor's action_space attribute is not automatically updated (nor does it reference directly its wrapped env's action_space).

So the fix is simple: reset the env directly after configuring it.

```
env_config={
...
"action": {                           
        "type": "ContinuousAction",
        "acceleration_range": [-5, 5.0],  
        "steering_range": [-np.pi / 4, np.pi / 4], 
        "longitudinal": True,             
        "lateral": True
    },
...
}
env = gym.make(env_config['id'])
env.unwrapped.configure(env_config)
env.reset()
env = wrappers.Monitor(env, log_path, video_callable=(None if env_config["display_record"] else False))
```

That should work.

**Comment by Exasor** [comment]
thanks a lot!

**Comment by Exasor** [comment]
I found another problem that the videos saved play very fast and record the last frame of previous episode, but don't display the first frame of this episode like this 

https://user-images.githubusercontent.com/56293255/109617311-31aeeb00-7b71-11eb-95f1-2bc2fd81f379.mp4

and my code is as follows:
```
for episode in range(1, 1 + n_episode):
    ...
    while not done:
        if display_record:
            env.render()
        ...
        if done:
            env.reset()
            ...
            break
env.close()
```
