### ISSUE TITLE
question about the info

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#141]
Sorry to bother you again, I want to add the reward information to `info` in `env.step()`:
```
info = {
            "speed": self.vehicle.speed,
            "crashed": self.vehicle.crashed,
            "action": action,
            "reward": [reward, right_lane_reward, high_speed_reward, steering_reward]
        }
```
but it warns that `KeyError: 'reward'`,  and I print info and find that the reward is not added, are there something I ignore?

**Comment by eleurent** [comment]
Where did you put this code exactly?
I tried it [here](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/abstract.py#L198) and it worked (with only the reward term, since the other terms are not in the scope of the step() function).

If it is a relevant feature that environments must return different kind of informations (these rewards terms that you want to include seem env-specific), I guess the proper way would be to add an `_info()` environment method, which can be overriden in specific env implementations.

**Comment by Exasor** [comment]
I modified the code according to your suggestion:
`highway_env\envs\common\abstract.py`
```
class AbstractEnv(gym.Env):
    def _info(self, obs: Observation, action: Action) -> dict:
        """
        Return a dictionary of additional information
        :param obs: current observation
        :param action: current action
        :return: info dict
        """
        info = {
            "speed": self.vehicle.speed,
            "crashed": self.vehicle.crashed,
            "action": action,
        }
        try:
            info["cost"] = self._cost(action)
        except NotImplementedError:
            pass
        return info

    def step(self, action: Action) -> Tuple[Observation, float, bool, dict]:
        ......
        info = self._info(obs, action)
```
`highway_env/envs/highway_env.py`
```
class HighwayEnv(AbstractEnv):
    def _reward(self, action: Action) :
        ......
        self.right_lane_reward = self.RIGHT_LANE_REWARD * lane / max(len(neighbours) - 1, 1)
        self.high_speed_reward = self.HIGH_SPEED_REWARD * np.clip(scaled_speed, 0, 1)
        self.steering_reward = self.STEERING_REWARD * scaled_steer

    def _info(self, obs: np.ndarray, action: int) -> dict:
        info = super()._info(obs, action)
        info["right_lane_reward"] = self.right_lane_reward
        info["high_speed_reward"] = self.high_speed_reward
        info["steering_reward"] = self.steering_reward
        return info
```
but it still shows the same error

**Comment by eleurent** [comment]
And which error is that? In your last code sample, you are not filling the "reward" info field.

**Comment by Exasor** [comment]
Yes, I delete the "reward",  and in my main program:
```
for episode in range(MAX_EPISODES):
    ......
    while not done:
        ......
        s_, r, done, info = env.step(a)
        ......
        ep_right_lane_reward += info["right_lane_reward"]
```
it warns: 
```
Traceback (most recent call last):
  File "DDPG.py", line 366, in <module>
    ep_right_lane_reward += info["right_lane_reward"]
KeyError: 'right_lane_reward'
```

**Comment by eleurent** [comment]
I just copied your code snippets and it works for me.
See the `print(info)` outputs:
```
{'speed': 25.0, 'crashed': False, 'action': 2, 'cost': 0.0, 'right_lane_reward': 0.10000000000000002, 'high_speed_reward': 0.2, 'steering_reward': 1}
{'speed': 29.1455588268693, 'crashed': False, 'action': 3, 'cost': 0.0, 'right_lane_reward': 0.10000000000000002, 'high_speed_reward': 0.36582235307477207, 'steering_reward': 1}
{'speed': 29.853986056331806, 'crashed': False, 'action': 2, 'cost': 0.0, 'right_lane_reward': 0.10000000000000002, 'high_speed_reward': 0.39415944225327226, 'steering_reward': 1}
{'speed': 25.82948910806644, 'crashed': False, 'action': 4, 'cost': 0.0, 'right_lane_reward': 0.10000000000000002, 'high_speed_reward': 0.23317956432265763, 'steering_reward': 1}
```

I do not really know how to help since I cannot reproduce the issue. I wonder what is going on on your side...
Are you sure that you are running your local code, rather than an installed previous version of highway-env?
(To make sure of that, I would advise to run pip uninstall highway-env and add your local clone to the python path)
Or you could try to run the script through a python debugger and see what goes wrong?

**Comment by Exasor** [comment]
Oh, I'm so careless, it is the previous installed version that was imported, and it works well now. Thanks for your patient guidance!
