### ISSUE TITLE
Realistic lane change duration for discrete actions

### ISSUE THREAD

**Issue by AkshayNemade** [eleurent/highway-env#144]
Is it possible to tweak the heading angle and/or duration of lane change in discrete actions? Realistically the switching of lanes is very gradual on highways with less heading angle. It would be great to see if the simulation an accommodate that. Any suggestions?

**Comment by eleurent** [comment]
Yes, the lane change dynamics were initially tuned it that way so that the highway problem could be described as a very simple MDP, where actions are taken every seconds and fully executed before the next timestep (to apply a value iteration).

But I agree that this is very unrealistic, and generally not required.

The duration of a lane change can be set by changing the [`KP_LATERAL`](https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/controller.py#L27) and KP_HEADING constants.
I'll try to come up with a better tuning.
