### ISSUE TITLE
A question about draw a colored rectangle.

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [eleurent/highway-env#149]
hello, thanks for your a nice job.
And i want to draw a colored rectangle to show extra information just as your demo which use colored rectangle to show different action values. And i find i can use viewer.add_geom in gym. But i can't use this function in this lib. 
So, what should i do if i want to draw a rectangle.
Thanks for your help.

**Comment by eleurent** [comment]
Hi @ZhenLiuBuaa,
highway-env does not have an `add_geom` method because I am using pygame for rendering, contrary to gym's classic_control envs' viewer which relies on OpenGL.

However, I also included a mechanism to show extra information: the EnvViewer class implements a set_agent_display method that you can use: https://github.com/eleurent/highway-env/blob/750b961289f9f048eb7d925ade7df385a451d0fb/highway_env/envs/common/graphics.py#L51

What this method does, is that it creates a free surface to display that additional information (typically related to the agent decisions, like action values). It takes an `agent_display` Callable argument, which should be a function that you provide. Then, everytime the environment is rendered it will call
`agent_display(agent_surface, sim_surface)`
where the first argument is the additional surface for agent information, and the second one is the usual simulation surface. Both can be modified by drawing various shapes.

As an example, see the function I wrote for a DQN agent, which plots the action values as colored rectangles and text: 
https://github.com/eleurent/rl-agents/blob/e4abed7233c6e727394ab9a671ee81761856e81a/rl_agents/agents/deep_q_network/graphics.py#L19

Note that this method has an additional `agent` argument, which must be set (using e.g. a lambda function, or functools.partial):
```
env = gym.make("highway-v0")
agent = DQN(env, ...)  # for instance
env.set_agent_display(functools.partial(DQNGraphics.display, agent=agent))

env.render()
```

**Comment by ZhenLiuBuaa** [comment]
Thanks for your quickly reply and it help me a lot.
