### ISSUE TITLE
Question about observation range and position mapping between simulation position and pixel position

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [eleurent/highway-env#150]
I am sorry to bother you again.
I have some confuses with the observation output. I find it doesnot have all vehicles and how can i   
change the observation range.
Another question is that i find the position of vehicle is not the pixel position of this vehicle. I should use the pixel position to do some visualization. So how can i get the vehicle's pixel position.
Thanks you very much.

**Comment by eleurent** [comment]
Hi @ZhenLiuBuaa  
There are several types of observations available, see https://highway-env.readthedocs.io/en/latest/observations/index.html

I am guessing that you are talking about the Kinematics observation.

* Indeed, not all vehicles are in the observation output, only those that are close enough. Right now, the observation range is set here: https://github.com/eleurent/highway-env/blob/d9c975c8afebd150fa5ff4e44562d4489574b237/highway_env/envs/common/abstract.py#L35
But I will move it to the parameters of the ObservationType, which is more suitable.
* Even if you increase the observation range, you may not be able to observe all vehicles in the scene since the observation must have a fixed size, which could me smaller than the total number of vehicles

If you really want to access the positions of all vehicles in the scene, maybe you should not use the observation but rather inspect directly the environment state:

```
for vehicle in env.road.vehicles:
    print(vehicle.position)
```

Now, the (x,y) position of each vehicle should be sufficient for your visualization needs: you can scale/offset them as you wish.
As an example, you can see/use the code I use for getting a pixel position from the original coordinate system, given a camera position and scaling:

https://github.com/eleurent/highway-env/blob/d9c975c8afebd150fa5ff4e44562d4489574b237/highway_env/road/graphics.py#L47

**Comment by zhen-liu-github** [comment]
Thanks for your advice and i find we can increase look_behind range to get more vehicles in observation.
https://github.com/eleurent/highway-env/blob/d9c975c8afebd150fa5ff4e44562d4489574b237/highway_env/road/road.py#L276
Here, we can increase 
2 * vehicle.LENGTH

**Comment by sunningshore** [comment]
> for vehicle in env.road.vehicles:
    print(vehicle.position)
Thanks for the explanation. This works in single agent scenario, the ego vehicle is always the first entry. However, in multi-agent scenarios, it is hard to identify the positions of the controled vehicles (as they are not the first entries). Is there any way to show the positions of controled vehicles in multi-agent scenarios?  Thanks!

**Comment by sunningshore** [comment]
`for vehicle in env.road.vehicles:
 print(vehicle.position)`

Thanks for the explanation. In single-agent cases, the controled vehicle is listed in the first entry. Just wondering is there any way to know which vehicle is the controlled vechicle in multi-agent scenarios? 
Thanks!

**Comment by eleurent** [comment]
You can get the list of controlled vehicles with `env.controlled_vehicles`.

(and `env.vehicle` returns the first controlled vehicle, which is the only one in the single-agent case)
