### ISSUE TITLE
Video Duration 

### ISSUE THREAD

**Issue by skynox03** [eleurent/highway-env#151]
Hi Eleurent!

I wanted to know, why are the saved video of a full episode is only 20 seconds long, even if the max episode duration is set to be 40 seconds?

**Comment by eleurent** [comment]
Hi!

This is because the video is recorded with a framerate of 30 fps (by default, since no value was provided in the env metadata), but the simulation runs (and generates frames) at 15hz. Thus, the video plays in x2 speed.

I will fix this by setting the video framerate metadata to the policy or simulation frequency.

**Comment by eleurent** [comment]
See https://highway-env.readthedocs.io/en/latest/faq.html
