### ISSUE TITLE
Question about the BicycleVehicle

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#152]
I noticed that in `derivative` method in class `BicycleVehicle(Vehicle)`, there is a part of low speed dynamics:
```
f_yf = - self.MASS * self.lateral_speed - self.INERTIA_Z/self.LENGTH_A * self.yaw_rate
f_yr = - self.MASS * self.lateral_speed + self.INERTIA_Z/self.LENGTH_A * self.yaw_rate
```
I wonder where the equations come from?

**Comment by Exasor** [comment]
I have some other questions about class `BicycleVehicle(Vehicle)`:
1. The inertia about the z-axis is
 `INERTIA_Z: float = 1/12 * MASS * (Vehicle.LENGTH ** 2 + 3 * Vehicle.WIDTH ** 2)`
and why to multiply the latter part by 3? The formula of the inertia movements of rectangular block is just
![图片](https://user-images.githubusercontent.com/56293255/112603162-91867200-8e4f-11eb-810b-b21e2f70ee3a.png)
2. According to (2.25) in _Vehicle Dynamics and Control. Rajamani, R._ , the `FRICTION_FRONT` refers to the cornering stiffness, but why it equals to `FRICTION_FRONT: float = 15.0 * MASS` ?

**Comment by eleurent** [comment]
> I noticed that in derivative method in class BicycleVehicle(Vehicle), there is a part of low speed dynamics:
> I wonder where the equations come from?

I think I wrote them myself because I was getting some instability with the original model from Rajmani, probably caused by the discontinuity of theta_f and theta_r when v_x=0? Honestly I do not quite remember, I'll make some tests to see what happens at low speed if I remove it.
Oh, and this low-speed model is absolutely not realistic, its is basically a magical proportional controller with a gain of 1.0 scaled by mass and inertia, such that all lateral motion is damped with a characteristic time of 1.0s.

>The inertia about the z-axis is
>INERTIA_Z: float = 1/12 * MASS * (Vehicle.LENGTH ** 2 + 3 * Vehicle.WIDTH ** 2)
>and why to multiply the latter part by 3? The formula of the inertia movements of rectangular block is just

That is because, apparently, in my world, cars look like cylinders. :sweat_smile:
Will change it, sorry about that.

> the FRICTION_FRONT refers to the cornering stiffness, but why it equals to FRICTION_FRONT: float = 15.0 * MASS ?

I wrote this as a way to normalize these stiffness coefficients by the mass. This way, instead of tuning m and C_\alpha separately, I can directly tune C_\alpha/m, which is the coefficient that matters for the dynamics. This is also why I use a value of 1 kg for the vehicle mass, it is basically a change of scale, and changing this value would not change the resulting trajectory. The value of 15.0 is homogeneous with an acceleration, in m.s^-2, whereas the stiffness is homogeneous with an force in N = kg.m.s^-2. 

Does that make sense?

**Comment by eleurent** [comment]
About the low-speed model, here is what happens with the original model when starting motionless and inputting a steering command for about 1s:
https://user-images.githubusercontent.com/1706935/112623854-275cd580-8e2d-11eb-8722-8eda2a18e8b5.mp4

Not exactly sure why, but the damping model I added was a dirty patch for that phenomenon.

**Comment by Exasor** [comment]
> I wrote this as a way to normalize these stiffness coefficients by the mass. This way, instead of tuning m and C_\alpha separately, I can directly tune C_\alpha/m, which is the coefficient that matters for the dynamics. This is also why I use a value of 1 kg for the vehicle mass, it is basically a change of scale, and changing this value would not change the resulting trajectory. The value of 15.0 is homogeneous with an acceleration, in m.s^-2, whereas the stiffness is homogeneous with an force in N = kg.m.s^-2.
Thanks a lot for your reply, but I don't quite understand your explanation, and I think using the data of inertia, stiffness and mass from Carsim directly may be easier and more interpretable?

**Comment by eleurent** [comment]
You're right, I agree with that.
