### ISSUE TITLE
record video according to the step

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#182]
Hi, I'm curious that if we can record the videos/episodes that last for specific steps or seconds, because in the defalut recording schedule, we can only record videos every certain episodes, but it may save many videos/episodes that are very short.

**Comment by eleurent** [comment]
Hi,
The rule of 1 episode/video is implemented in the original Monitor/VideoRecorder class of openai gym.
I agree that if the episode is short, your video will not be very informative.

I see a few possibilities to address your issue:
1. change the `video_callable` function (which specifies which episodes should be recorded) in order to record more episodes, like 10 successive episodes every 1000 episodes, rather than 1 episode every 1000 episode (as is default, after the cubic progression)
2. Wrap the environment into a [VecVideoRecorder](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#stable_baselines.common.vec_env.VecVideoRecorder), from stable_baselines, which accepts a fixed video length
3. Wrap the environment into a Wrapper which ignores terminal states and automatically calls env.reset(), so that the video is not interrupted when there is a collision. This wrapper can then be wrapped into a TimeLimit wrapper with the desired duration.
4. Modify the VideoRecorder code from `gym.wrappers.monitoring import video_recorder` to reset after a fixed duration instead of terminal state, but that is probably going to be the hardest solution

**Comment by Exasor** [comment]
Thanks a lot for your suggestion!
