### ISSUE TITLE
Question about extraction a single lane for the road.network.lane_list()

### ISSUE THREAD

**Issue by Andrealberti** [eleurent/highway-env#191]
Hi, I am working with the parking-v0 environment, I am trying to config a specific scenario with two parked vehicles and a static goal between them. 
To avoid the creation of a random goal I was wondering to modify this line in the parking_env.py file:
`lane = self.np_random.choice(self.road.network.lanes_list())`
and choose one of the list's lane in particular, but I don't understand how to index a single lane due to the object type.
Can you help me with that? Thanks in advance.

**Comment by eleurent** [comment]
Hi @Andrealberti 

A set of parallel lanes is considered as part of a single road segment, which is indexed by two labels representing its start and end locations (these labels are only used for the network topology, to search for connected routes)

In parking, we have 2 rows of parking spots, which are represented by two "roads", the bottom one ("a"->"b"), and the top one ("b"->"c") (here "a" represents the south of the parking, "b" is the middle area, and "c" is the northern region, although it does not really matter in this case since these are not connected roads).

And then, to get a particular lane in the road, you can simply refer to it by an index. In the end, a LaneIndex is a tuple (start label, end label, lane index) used to index any lane in the network.

For instance, to get the 3rd spot of the top row, you can simply call
`self.road.network.get_lane(("b", "c", 2))`

**Comment by Andrealberti** [comment]
Thank you so much,  I was trying to use the wrong function with the right indices.

**Comment by Andrealberti** [comment]
Sorry, another question. I have tried to implement what I was talking about, but I think that the parking environment doesn't take in account collisions with other vehicles/obstacles in the reward computation, in fact I obtained very bad results training the HER algorithm with SAC policy.  @eleurent Have you ever tried to implement a simil scenario?

**Comment by eleurent** [comment]
Indeed, not having a collision penalty is problematic, especially since the reward function is negative, which provides an incentive for the vehicle to get to a terminal state as fast as possible.

Adding a collision penalty could fix it, and making the rewards positive (using 1/(1+d) or exp(-d) rather than -d for instance) is an even better choice.

Though I haven't tried it myself, the Summon env by Vinny Ruia is a variant of parking-v0 which includes obstacles and a collision penalty.
However, these obstacles are placed randomly, which means that they should be added to the observation for the agent to be able to avoid them, and I don't think that is the case for now.

TODO: 
- [ ] Make rewards positive
- [ ] Add an observation type that features {vehicle location, goal location, obstacle locations} and can be used natively by goal-conditioned policies.
