### ISSUE TITLE
How to collect data from the highway simulator?

### ISSUE THREAD

**Issue by Xiaoyu006** [eleurent/highway-env#198]
Hi, Eleurent,

Thank you very much for this wonderful RL environment. 

I currently would like to collect some data by running the intersection env many times.
The data will be like a pandas DataFrame containing each vehicle's state sequences throughout the simulation. An example of the wanted data could be found here: https://interaction-dataset.com/details-and-format. 

I seek for you quick suggestions on:
1. How to run the simulator without the ego vehicle, without training? All the vehicles are controlled by IMD vehicles.
2. How to collect the data?
        1. states sequences of each vehicle [#vehicles, timestamps, [x, y, vx, vy, yaw] at each time stamp] in a shared coordinate system.
        2. I tried to store data from kinematics observation and found the collected trajectory of #1 vehicle looks reasonable while for the rest of the vehicles, the collected trajectories are weird. One possible reason I guess is that the obs matrix works as a queue.

I look forward to your suggestions!

Please have a nice weekend!

Xiaoyu

**Comment by eleurent** [comment]
Hi @Xiaoyu006 

Here is a code snipped that should fit your requirements:
1. the ego-vehicle is removed from the scene
2. the data are directly collected from dictionary descriptions of each vehicle, rather than relying on observations. This is probably more flexible and easier to customize than directly using observations (the reason why you may have found the kinematics observations weird is because different kind of normalizations are used for ego vs other vehicles)

```
import gym
import highway_env
import pandas as pd


env = gym.make('intersection-v0')
env.road.vehicles.remove(env.vehicle)  # Remove the controlled vehicle from the scene

n_episodes = 1
data = []
for episode in range(n_episodes):
    time, done = 0, False
    while not done:
        for vehicle in env.road.vehicles:
            data.append({'time': time, 'id': id(vehicle), **vehicle.to_dict()})
        _, _, done, _ = env.step(0)
        time += 1
env.close()
data = pd.DataFrame(data)
print(data)
```

**Comment by Xiaoyu006** [comment]
Hi @eleurent,

Thank you for your quick reply and the code! 
It helps a lot! Thank you very much!

Xiaoyu
