### ISSUE TITLE
Question around best rewards

### ISSUE THREAD

**Issue by hougiebear** [eleurent/highway-env#203]
Possibly a dumb question but I was wondering is there any way to determine the best rewards for the default environment configuration or do you have this information readily available? For instance in highway-v0, for a duration of 40 seconds without collisions it should be

reward =  + self.config["collision_reward"] * self.vehicle.crashed + self.config["right_lane_reward"] * lane / max(len(neighbours) - 1, 1)  + self.config["high_speed_reward"] * np.clip(scaled_speed, 0, 1)

So no collisions for duration of 40 seconds = (-1 * 0) + (0.1 * 1 )+ (0.4 * 1) = 0.5 per second? So it would be 20 seconds? if we used frequency of 2, it would be a maxium of 40?

**Comment by eleurent** [comment]
Hi!
I generally try to scale the rewards in the [0, 1] range:

https://github.com/eleurent/highway-env/blob/0d0d78f6cbfaf188fbcf9051d826a946e518bd5c/highway_env/envs/highway_env.py#L92

which means that the optimal total reward for H steps is ~H.
So for 40s at 1Hz, it would be around 40.
And yes, if you increase the policy frequency to 2Hz, that doubles the number of steps and the total reward is now upper-bounded by 80.

A suboptimal but collision-free behaviour should be closer to a per-step reward of 0.5, rather than 1, which would give a total reward of 0.5*H = 20.

**Comment by hougiebear** [comment]
Perfect thank you.  That makes sense, I see some of the start of the art algorithms hitting around 37-38 with policy set to 1Hz so expected this. The reason I was asking for clarification is I was seeing rewards of sub-20 with no crashes detected in the env.info
