### ISSUE TITLE
The order of observation

### ISSUE THREAD

**Issue by lxpr** [eleurent/highway-env#211]
Hi, I am trying to get the "Kinematic" type observation of several surrounding vehicles simultaneously and make the positions of one vehicle at different time steps a list. However, even if I configure the "order" parameter to be "sorted", the order of different vehicles seems to change at some steps. Below is an example of the x positions of 11 vehicles (simplified to be integers). One line represents a step.
25 23 31 11 43 05 52 54 64 72 79
26 26 32 13 08 44 54 55 65 74 81
27 28 34 14 11 45 56 57 67 76 82
28 31 35 15 13 46 56 59 68 78 84
32 33 37 46 16 15 57 61 70 80 86
36 35 39 47 18 17 58 63 71 82 87 
40 40 38 47 58 19 19 65 73 84 89
In the second step, vehicle 5 and 6 seem to have swaped their order. In the 5th step, vehicle 4 and 6 seem to have swaped their order. The same thing happens at the 7th step for vehicle 5 and 7.

**Comment by eleurent** [comment]
Hi,
The sorted order parameter sorts the observed vehicles by increasing absolute distance to the agent. 
Thus, it is expected that the order changes between steps, since these distances also change. Also, the y coordinate is involved in the order computation, which could explain why two x coordinates are swapped.

The main purpose of this ordering is simply to have a convention such that a given traffic state is always described by the same vector, chosen as an (arbitrary) representative, and to avoid the aliasing of the N! possible orderings of N vehicles.

If you require a representation that preserves the order of vehicles through time, it is best that you implement you own observation type to suit your needs (and possibly open a pull request to contribute :) )

**Comment by lxpr** [comment]
Hi, 
Thank you very much. I have modified observation.py and implemented a representation that preserves the order of vehicles through time. I just removed the sorting line for the new type of observation.

**Comment by eleurent** [comment]
I just realized that the order = "sorted" parameter had no effect on the actual sorting.
You should now have the intended behavior by using e.g. order = "fixed" (or anything different than sorted and shuffled).
