### ISSUE TITLE
the reward function - _reward() 

### ISSUE THREAD

**Issue by yael-ai** [eleurent/highway-env#241]
Hello,
I am wondering about the _reward function.
In the function the reward is calculated as following:
reward = \
            + self.config["collision_reward"] * self.vehicle.crashed \
            + self.config["right_lane_reward"] * lane / max(len(neighbours) - 1, 1) \
            + self.config["high_speed_reward"] * np.clip(scaled_speed, 0, 1)
        reward = utils.lmap(reward,
                          [self.config["collision_reward"],
                           self.config["high_speed_reward"] + self.config["right_lane_reward"]],
                          [0, 1])
        reward = 0 if not self.vehicle.on_road else reward
        return reward

If I set in my configuration file that right_lane_reward and high_speed_reward are set to zero and collision_reward as a negative number shouldn't this function always return 0?
I get different values that are bigger the zero and I don't understand why 
Thanks in advance,
Yael

**Comment by eleurent** [comment]
Hi @yael-ai 
This is probably due to the reward normalization in the [0, 1] range. 

Indeed, if you set high_speed_reward = right_lane_reward = 0, and e.g. collision reward = -5, then the reward is linearly mapped from the [-5, 0] range to [0, 1]. 
So a collision-free state should always give a reward r=1 (after the mapping, instead of r=0). 
Is that what you observe?

**Comment by yael-ai** [comment]
Hi,
Thank you so much for the response!
Yes it makes sense now
