### ISSUE TITLE
would like to observe the image of each agent keep the center constant when the observed car changes lane

### ISSUE THREAD

**Issue by LianhaoYin** [eleurent/highway-env#244]
In MultiAgentObservation, would like to observe the image of each agent keep the center constant when the observed car changes lane.

Is it possible to make such a change?

**Comment by eleurent** [comment]
Hi @LianhaoYin 
The center position of the rendered image is controlled here
https://github.com/eleurent/highway-env/blob/3f569cfa766b454d545fcf048be3f7fb46f8a11a/highway_env/envs/common/graphics.py#L149

Right now, it uses the position of the observer vehicle (I just patched it because it used to only track the 1st controlled vehicle, I had left the per-observer centering as a todo). 
You can change it to e.g. use the x position of the observer vehicle but a constant y position.
