### ISSUE TITLE
speed is 0

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#248]
hi
why  speed of the control vehicle can not  equal 0？

**Comment by eleurent** [comment]
Hi @piccupl 
If you are using discrete meta actions, the vehicle has a minimum speed which can be changed here:
https://github.com/eleurent/highway-env/blob/d21a768a9857ca4d04d53e0a7b98fb9840398c3f/highway_env/vehicle/controller.py#L208

Basically, the speeds that the vehicle can track are discretised as `np.linspace(SPEED_MIN, SPEED_MAX, SPEED_COUNT)`.

I should really make these parameters configurable rather than constants, though.

**Comment by eleurent** [comment]
I pushed a patch, after updating you can now set the speeds that the vehicle can follow with, for instance:
```
env.configure({
    "action": {
        "type": "DiscreteMetaAction",
        "target_speeds": [0, 5, 10]
    }
})
```
