### ISSUE TITLE
condition of the end of an epoch and the environmental vehicles will change

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#252]
hi @eleurent 
thanks for your replay for the issue 247.
I have the three questions when using this environment.
1、I want to know what is the condition of the end of an epoch，I noticed that the game ended without any collision.
2、When the speed of the environmental vehicles are 0, the direction of the environmental vehicles will change.
![M63L1ZMD5Z`%2ZM0AEIV JA](https://user-images.githubusercontent.com/26081938/147766924-6789d2ac-9977-475c-b4f7-9e41e52ff377.png)
3、There's one last question I'd like to discuss with you。If my neural network outputs an unavailable action，Taking an unavailable action is equivalent to taking the IDLE action.So how can I train my neural network to be more effective？

I've searched for several methods.But I'd like to hear your opinion
1、If the neural network outputs an unavailable action，and  the game is restarted
2、If the neural network outputs an unavailable action，Setting a large negative reward value
3、If the neural network outputs an unavailable action，mask the probability distribution of actions

**Comment by eleurent** [comment]
1. The terminal conditions depend on the environment, you can find them in the `_is_terminal()` method. Generally, episodes have a maximum duration, but you can set it to a very high value if you don't need it.
2. The vehicles a probably trying to change lane. If their speed oscillate around 0, it may be enough for them to start turning slowly. I'll write a patch.
3. This is really an open question. You mentioned three options, four if we include the one of using IDLE instead of any unavailable action. I think all of them are relevant, and I have seen all of them used in the literature. It is very likely that their efficiency depend on the actual environment you are trying to solve, and also on which kind of RL algorithm you are using. _For instance, even inside the family of MCTS algorithms, some algorithms (like OPD) work better if there is a narrow optimal path, while others (UCT) prefer to explore large near-optimal regions_. My advice would be try them all, ans see what works best in your case.
