### ISSUE TITLE
Can MCTS agent runs in real-time?

### ISSUE THREAD

**Issue by dongleecsu** [eleurent/highway-env#26]
Hi Eleurent,

Thank you for the great repo! 
The performance of the MCTS agent looks amazing in the last GIF (in this repo's README). And I tried to run the MCTS agent [(configs)](https://github.com/eleurent/rl-agents/tree/master/scripts/configs/HighwayEnv/agents/MCTSAgent) from `rl-agent` repo on the `highway-v0` task. But it seemed the agent cannot control the vehicle in real-time. The performance was also not as good as in the MCTS GIF. 
Are there any further configurations I missed? or the MCTS algorithm itself is hard to run in real-time?

Thanks,
Dong

**Comment by eleurent** [comment]
Hi @dongleecsu 

Regarding performances, I think I used the [https://github.com/eleurent/rl-agents/blob/master/scripts/configs/HighwayEnv/agents/MCTSAgent/baseline.json](baseline.json) at the time to make this gif. But there has been some refactoring since then, and the default configs may have changed in the meantime. You can try to tune the available budget / temperature / step strategy to increase the performances.

But MCTS (in fact, UCT) is actually not the best-performing monte-carlo tree-search agent, you should tried [OPD](https://github.com/eleurent/rl-agents/blob/master/scripts/configs/HighwayEnv/agents/DeterministicPlannerAgent/baseline.json) instead.
It does a much better job with a lower simulation budget (and is hence also faster to run), at the expense of only being able to deal with deterministic rewards & dynamics.

Now, about real-time execution, I'd say that it is indeed a limitation of MCTS algorithms given that they depend on the ability to run dozens/hundreds of simulations as fast as possible.
Now, this problem is particularly significant with this higway-env environment, which was conceived mainly for easy prototyping of environments / scenarios, and not at all for high-performance simulation. The simulation is done in Python which is already pretty slow, and the code is not properly optimized, because it was not really the intent. For a more practical application, many steps could be taken such as rewriting the simulator in C++, using parallel computing in the planning algorithm, etc., but it is not in the scope of this project.

Edouard

**Comment by dongleecsu** [comment]
Thank you, Edouard. The OPD agent is pretty efficient and behaves much better.
