### ISSUE TITLE
Help to understand the controller: yaw rate to steering angle

### ISSUE THREAD

**Issue by liuxin00738** [eleurent/highway-env#262]
Hi Edouard,

Thanks for the repo! Can you help me understand how you convert the yaw rate to steering angle? 
https://highway-env.readthedocs.io/en/latest/dynamics/vehicle/controller.html 

The v here refers to the speed at the center of the vehicle, right?

I feel it should be delta = atan( 2* asin (l*d_psi/v)?

**Comment by eleurent** [comment]
Hi @liuxin00738 
Sorry for the late answer, you're right there was something wrong in the formula.
Basically, I'm converting heading rate to steering angle by inverting the kinematics: https://highway-env.readthedocs.io/en/latest/dynamics/vehicle/kinematics.html#vehicle-kinematics
The problem is that I used to use the slip angle `beta = asin(l/v * d_psi)` as the steering command directly, in an old version of the kinematics were the steering wheel angle delta was not included for the sake of simplicity. When I introduced delta in the kinematic model, I forgot to update this controller. 

I have not fixed it, with
```
beta = asin(l/v * d_psi)
delta = atan(2*tan(beta))
```
