### ISSUE TITLE
visualizing results

### ISSUE THREAD

**Issue by srianumakonda** [eleurent/highway-env#263]
hey! probably a very trivial question but am wondering where in the documentation did you can visualize trajectories (for DQNs + MC Tree Search).

**Comment by eleurent** [comment]
Hey, very legitimate question since it's actually not documented :/
Once the environment viewer has been created (you need to call `env.render()` once), you can visualize a planned sequence of actions `actions` by calling [env.viewer.set_agent_action_sequence(actions)](https://github.com/eleurent/highway-env/blob/aaccbf293ab2549fd30dfb816853aa22b1e82754/highway_env/envs/common/graphics.py#L70).

**Comment by srianumakonda** [comment]
got it - also am wondering about the visualizing for the DQN (the square one - think values are estimating Q function iirc). thanks so much!

**Comment by eleurent** [comment]
Yes, the color squares represent the Q-values, exactly.
The visualization of the DQN is done in the same repo where the DQN agent is implemented, [rl-agents](https://github.com/eleurent/rl-agents) (this highway-env repo only describes the environment).
More precisely, it is implemented here:
https://github.com/eleurent/rl-agents/blob/d55126007fcc5d2a882843f6c3a63000b4fc7c92/rl_agents/agents/deep_q_network/graphics.py#L19

If you run an episode using the rl-agents codebase, this display should be enabled by default.

**Comment by srianumakonda** [comment]
great! appreciate the help, closing issue for now - will reopen if anything pops up. thanks a lot :)

**Comment by eleurent** [comment]
Yes absolutely!
