### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by songanz** [eleurent/highway-env#27]
Hi eleurent,

Thank you very much for your excellent work. I also noticed that you have another repo "rl-agents" for training agents in this environment. I have set up the DQN agents using your baseline config. However, I cannot generate a policy like your Gif. Could you please help me?

**Comment by songanz** [comment]
And I cannot run most of your "rl-agents" config. which use different algorithms. Some of them have trouble saving the trained models.

**Comment by eleurent** [comment]
Hi @songanz,
The DQN gif on the Readme was generated about a year ago, and both the environment and agent source codes have evolved since, it is possible that some further tuning is required. 
I'll try to run a training again and get back to you.

>  I cannot run most of your "rl-agents" config. which use different algorithms. Some of them have trouble saving the trained models.
Which agents are you talking about exactly? For some agents there is simply no training phase / model to save, so they may produce a simple warning when loading them.

**Comment by eleurent** [comment]
The current config dates from last may, see: https://github.com/eleurent/rl-agents/issues/21

**Comment by eleurent** [comment]
Thank you very much for the feedback, there was indeed a regression caused by the recent refactoring of observations: the vehicles used to be sorted by increasing distance, but were not anymore.
I reverted to this behaviour as default, since it is helps simple models to converge (front vehicles are always in the first rows of the input tensor).

Here are the results I get, before (red) and after the fix (grey).
![episode](https://user-images.githubusercontent.com/1706935/68627126-45968f80-04dd-11ea-88c2-fa1fa654ca0b.PNG)

You can try to updgrade and run `experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/baseline.json --train --episodes=1500`.
Let me know if this helped :)

**Comment by songanz** [comment]
Thank you very much for your excellent work. I will give a try latter.

**Comment by songanz** [comment]
By the way, what should I do if I want to cite your rl-agents repo?

**Comment by eleurent** [comment]
Thanks for asking!
I added a bibtex in the readme: https://github.com/eleurent/rl-agents#citing

**Comment by songanz** [comment]
I have tried your newer version and I get the same result as in your reply. Thank you very much. 

> Thank you very much for the feedback, there was indeed a regression caused by the recent refactoring of observations: the vehicles used to be sorted by increasing distance, but were not anymore.
> I reverted to this behaviour as default, since it is helps simple models to converge (front vehicles are always in the first rows of the input tensor).
> 
> Here are the results I get, before (red) and after the fix (grey).
> ![episode](https://user-images.githubusercontent.com/1706935/68627126-45968f80-04dd-11ea-88c2-fa1fa654ca0b.PNG)
> 
> You can try to updgrade and run `experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/baseline.json --train --episodes=1500`.
> Let me know if this helped :)
