### ISSUE TITLE
Question about discreteMetaAction

### ISSUE THREAD

**Issue by Cuizy-faiz** [eleurent/highway-env#278]
Hi，@eleurent！DiscreteMetaAction has an attribution target_speeds. I can't understand its meaning. For example, in roundabout_env, Its default value is [0,8,16]. What does each dimension of [0,8,16] mean ? 
Furthermore, I want to apply hierarchical RL on roundabout_env, such as choose metaAction->choose target_speed. How to change the value of  target_speed during training?  Do I have to change the environment configuration every time ?

**Comment by eleurent** [comment]
The current `DiscreteMetaAction` has the following behaviour: to control the speed of the vehicle, the agent can choose between the actions `SLOWER `/ `IDLE `/ `FASTER`. This sets the target speed to the previous / same / next value in the `target_speeds` config of `DiscreteMetaAction`, which is a list of speeds in m/s. So for example, if the vehicle is initialised with a target speed of 8m/s, using FASTER will change its target speed to 16m/s, and if the value of 20 is added to the config, then doing FASTER again would change it to 20 m/s.

I think your use case of studying a hierarchical action space is very interesting, but maybe the current `DiscreteMetaAction` action type is not really suited for that, because actions correspond to relative changes (increase/decrease) in speed rather than setting an absolute speed. I think it would be best to add a new observation type, where N different speeds can be set (from the same `target_speed` config), and where N discrete actions are available, to set the speed to each of these values (rather than the current 3 actions, regardless of N).

Does that make sense?

**Comment by Cuizy-faiz** [comment]
Thank you very much ! It's so clearly
