### ISSUE TITLE
how to get the distance to the front vehicle

### ISSUE THREAD

**Issue by chenxiaochang** [eleurent/highway-env#280]
How to get the longitudinal distance of two cars in the Frenet coordinate system if they are in different lanes of the road. 

For example, the ego vehicle is on a straight lane, and the preceding vehicle is on a connected circular lane， how can I get the distance between two vehicles along the lanes.

thanks for your reply.

**Comment by LTsommer** [comment]
In the file highway-env/highway-env/road/spline.py introduced the tf of frenet coordinate and cartesian coordinate. You can first transfer their coordinates from cartesian to frenet, and then simply use their longitudinal distance to minus each other no matter whether they are in the same lane, because the distance in longitudianl direction in frenet coodinate in the same road is the one and only, but the lateral offset are different.

**Comment by eleurent** [comment]
Hi @chenxiaochang,
I think that is a very tricky question in general.
At some point, I set out to implementing a way of computing longitudinal distances between any two locations that was supposed to be general, but that actually doesnt make much sense in many situations, in particular when there is no route that leads from the first positions to the second one.
For example, consider a merging road:
A ->- 
         \
           B --->
          /
->- C
What is the longitudinal distance between A and C in this case?

So I kind of abandoned the idea at the time, and have relied on very simple heuristics since, which can also be wrong in many situation: if I remember correctly, in your situation, I typically compute the longitudinal position of the preceding vehicle as if it was on the ego-vehicle lane (which is basically equivalent to doing a projection).
It's not ideal, but it was enough in my use cases.

As @LTsommer relevantly pointed out, if you are guaranteed to have a feasible route between the ego and its preceding vehicle, e.g. if both are on the same road which is composed of several segments like a spline, then it makes sense to iterate through each intermediate segments and adding their length (which is what the cartesian -> frenet conversion does)

**Comment by chenxiaochang** [comment]
Thank you very much for your help.
