### ISSUE TITLE
Why does the car always stop in the CircularLane?

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#284]
Hello, why when using DQN to train the car, after the 10,000th episodes, the car frequently stops at the circularlane. Neither collision nor exit?

**Comment by eleurent** [comment]
Hello, 
Difficult to say, maybe something is wrong in your training setting (observation type, model architecture, etc. not suitable for the task)? For example, if the model cannot make use of its observation to understand where other vehicles are, it is basically blind and could be incentivized to slow down / stop to decrease the collision probability... But that's just a hypothesis, it could be many things.

**Comment by tingtingLiuLiu** [comment]
I use the KinematicObservation method  for Observation , I'll take a closer look. Thank you very much for your help.

**Comment by seominseok00** [comment]
@tingtingLiuLiu I'm using IntersectionEnv, and I've encountered a problem similar to yours. Have you managed to resolve it?

**Comment by eleurent** [comment]
For intersection env (or other envs), I would suggest using an attention-based architecture so that the agent can better take into account the  positions / speeds of other vehicles and whether they represent a collision threat or not.
With the default MLP model, the agent has a hard time understanding if vehicles are going to collide with them or not, so it typically adopts more conservative behaviours.

See paper: https://arxiv.org/abs/1911.12250
Colab: https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb

**Comment by seominseok00** [comment]
@eleurent I was just reading that paper! Can I train in my custom environment as well?

[image](https://github.com/Farama-Foundation/HighwayEnv/assets/110466566/387ce97e-b685-4c74-9a3e-772741e6f053)

**Comment by eleurent** [comment]
Yes, you should be able to adapt the colab to change the environment.

**Comment by seominseok00** [comment]
@eleurent I'm running the colab code you provided on my local machine, and while training is working, I'm encountering an error when I try to run the evaluation. Could you please help me with this?

[TypeError: must be real number, not NoneType](https://github.com/eleurent/rl-agents/issues/106)
