### ISSUE TITLE
Problems with control

### ISSUE THREAD

**Issue by HUXIAOWANG513** [eleurent/highway-env#300]
Dear eleurent:
        You pointed out in the document that in the execution of discrete strategies, such as DQN algorithm, we first select actions through the Q value output by DNN, and then refine control details (such as acceleration, Angle) through a PID algorithm. I wonder if I got it right?

**Comment by eleurent** [comment]
Yes, that is what happens when you set the action type to [DiscreteMetaActions](https://highway-env.readthedocs.io/en/latest/actions/index.html#discrete-meta-actions) (which is the default).
The RL agent's actions set the speed and lateral position setpoints, which are then tracked by low-level controllers (PID) to produce controls (gas pedal, steering angle).

**Comment by HUXIAOWANG513** [comment]
OK, thank you very much for your guidance!
