### ISSUE TITLE
parking_model_based.ipynb google cloab has error

### ISSUE THREAD

**Issue by 945716994** [eleurent/highway-env#305]
While i run the parking_model_based.ipynb example, the google cloab get a error: ImportError: cannot import name 'RecordVideo' from 'gym.wrappers' 。

**Comment by eleurent** [comment]
Interesting, apparently gym==0.17.3 is installed by default on Colab, but the RecordVideo wrapper only appeared on gym==0.21 or 0.22.
I recently made it a required dependency of highway-env, but I havent generated a stable version with this change yet, which is why the gym version does not get upgraded automatically when installing stable highway env.

In the meantime, you can fix it either by installing the dev version of highway env; i.e.
replace
`!pip install highway-env`
by
`!pip install git+https://github.com/eleurent/highway-env`

or alternatively simply add 
!pip install gym==0.23.1
in the beginning.
