### ISSUE TITLE
Pitfall in control level policy

### ISSUE THREAD

**Issue by zerongxi** [eleurent/highway-env#312]
In the default setting in highway-v0, the reward is linearly mapped from [-1 (collision), 0.5 (full speed + right lane)] to [0, 1]. Therefore, the agent receives at least 0.66 for surviving at each policy step. However, because all the vehicles are created in front of the agent, the agent can easily survive and receive considerable rewards by slowing down or even parking on the highway, which is very unrealistic. This issue is avoided in DiscreteMetaAction because the lowest target speed can be limited. But I have observed learned ContinuousAction policies perform this strategy, especially when the problem becomes harder, e.g. with higher vehicle density.

While I agree that collision should be seriously penalized (or surviving being continuously rewarded as the current env do), there may be a few ways to fix that:
1) add a low-speed limit on ContinuousAction/DiscreteAction as well;
2) create vehicles both in front of and behind the agent, so that it has the risk of collision for being too slow.

**Comment by zerongxi** [comment]
I observed something else interesting. As long as there is no low-speed limit on x-axis, some learned policies slow down/stop/circle/move in opposite direction at the beginning to get away from the traffic, then run at full speed to get rewards. Seems to be a good strategy if there is no speed limit and being promised that no traffic from behind, even when driving in the real world.

**Comment by eleurent** [comment]
Hi! Indeed, this environment was initially developed for high-level decisions, and the support of continuous actions was added later, so the reward etc. is not perfectly suited, and all the modifications you suggested definitely make sense.
The mapping of the reward can currently be configured, but it would probably be valuable to add a configurable min & max speed for continuous actions.
Adding traffic from behind can also be done, but in theory they should not really incentivize the agent to drive faster as they are supposed to slow down and stop before an obstacle. It would probably help with your second use case though, another possibility is to ensure that the dot product between velocity and lane heading is high, rather than the vehicle speed.
