### ISSUE TITLE
Visualising Nodes in Road Graph

### ISSUE THREAD

**Issue by TibiGG** [eleurent/highway-env#319]
Hi @eleurent,

I was interested in making my own road layout for my project, but I am having a bit of a hard time setting up the lanes to connect correctly. Is there any way to visualise the nodes during debugging, to make sure they are positioned correctly?

Thanks!
Tibi

**Comment by piccupl** [comment]
I also very intI also very interested in the problem.When creating a vehicle.
I have a question about creating vehicles：
`other_vehicles_type(road, road.network.get_lane(("j", "k", 0)).position(110, 0), speed=20)`
Do I only need to specify the longitudinal displacement 110？ erested in the problem.When creating a vehicle.

**Comment by eleurent** [comment]
Hi TibiGG.
I am not sure what you mean exactly, since the nodes do not have positions: they are only abstract vertices in the graph which defines the topological road network, i.e. which road is connected to which other road. The edges of this graph however, that link two nodes, have geometries, and these can be rendered.
For instance, you could render e.g. a green dot at the beginning of each lane segment (`lane.position(0, 0)`), and a red dot at the end (`lane.position(lane.length, 0)`).
Does that make sense?

**Comment by eleurent** [comment]
@piccupl not sure about your question either, you can specify the longitudinal displacement to any value you want, and you can also set a lateral displacement. Alternatively, you can set any cartesian position (x,y) that you like directly, without resorting to `get_lane(...).position(...)`
