### ISSUE TITLE
merging issue

### ISSUE THREAD

**Issue by LawranceXcl** [eleurent/highway-env#32]
Ok! Done successfully! Thks!
Aiming at the merging env, do you also use the rl algorithm?And I can see that the host vehicle is in the main lane, I wonder if the method of RL algorithm you did can handle the case where the host vehicle is in the ramp. Before the acceleration lane of ramp is end, the host can merging into the main lane successfully.

**Comment by eleurent** [comment]
> Aiming at the merging env, do you also use the rl algorithm?

In that case, it was a planning (tree search) algorithm, but other rl algorithms can also be used (dqn, etc) in the `rl-agents` package.

> Handle the case where the host vehicle is in the ramp

Feel free to modify the `merge.py` environment so that the host vehicle begins on the access ramp. If needed, you can also adjust the reward function. And do not hesitate to contribute with a pull request.
