### ISSUE TITLE
the function of create_random

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#324]
on the road (j,k,0) of  merge-v0
I use Create_random to create traffic flow.
The code is as follows
```
for others in other_per_controlled:
            vehicle = Vehicle.create_random(
                self.road,
                speed=25,
                lane_from= "j",
                lane_to = "k",
                lane_id=0,
                spacing=self.config["ego_spacing"]
            )
            vehicle = self.action_type.vehicle_class(self.road, vehicle.position, vehicle.heading, vehicle.speed)
            self.controlled_vehicles.append(vehicle)
            self.road.vehicles.append(vehicle)
```
But the generated vehicle is not on the  road (j,k,0)
the result as follows:
![Figure_1](https://user-images.githubusercontent.com/26081938/170878962-b908cd0f-ef44-40e6-8308-7fcacbd00c19.png)

**Comment by eleurent** [comment]
This is because they are create on the (i, j) lane with a longitudinal coordinate much larger than the lane length.
Try reducing the `ego_spacing`, and creating the controlled vehicles first (because create random always adds vehicle at the end of the lane, after any previously created vehicles).
Otherwise, maybe don't use `create_random`, and set their position directly with `get_lane(...).position(...)`
