### ISSUE TITLE
Converting `highway-v0` to continuous control

### ISSUE THREAD

**Issue by angelolovatto** [eleurent/highway-env#33]
Hello! I'd like to know what is the best way to make a version of `highway-v0` with continuous controls (steering and acceleration). 

Looking at the source code, I reckon that the most straightforward way would be to implement a subclass of `HighwayEnv` and override its `step` method. It would then call 
```python
self.vehicle.act(
    {"acceleration": action[0] * self.ACCELERATION_RANGE,
    "steering": action[1] * self.STEERING_RANGE}
)
```
and then `self.simulate()` with no arguments, bypassing the automatic steering and acceleration presets. 

However, I'm not sure how to detect lane changes, which are necessary for calculating the reward. Any help would be appreciated, as there's quite a bit of code to look at.

Great job with the simulations btw!

**Comment by eleurent** [comment]
Hi Angelo, thanks a lot!

The steps you described for performing continuous action look perfectly right to me, you can look into [ParkingEnv](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/parking_env.py#L49) for an example continuous control task.

Regarding the detection of lane changes, you can recover the current lane of the ego vehicle in the reward function using
```
def _reward(self):
    start, end, idx= self.vehicle.lane_index
    ... your code here
```
`start` and `end` are symbols representing the starting and ending locations of the road (used to define road networks). `idx` is the actual index of the lane on that road.

Does that help?

**Comment by eleurent** [comment]
Note that if the car goes offroad, using `vehicle.lane_index` will (probably) still return the index of the closest lane. Thus, you may need an additional check to verify that the vehicle is actually on the lane:
```
vehicle.lane.on_lane(vehicle.position)
```

**Comment by angelolovatto** [comment]
Hi Edouard, thanks for the feedback! That seems exactly like what I'm looking for! I'll update you on the results. Looking forward to experimenting with the framework. Best regards.

**Comment by angelolovatto** [comment]
Hi Edouard, I managed to get it working using your tips and by overriding `MDPVehicle`'s `act` method to take in raw acceleration and steering actions
```python
class MyVehicle(MDPVehicle):
    """MDPVehicle with low-level actions."""

    @override(MDPVehicle)
    def act(self, action=None):
        Vehicle.act(self, action)
```
and in the environment
```python
    @override(HighwayEnv)
    def _create_vehicles(self):
        self.vehicle = MyVehicle(
            self.road, [0, 0], 2 * np.pi * self.np_random.rand(), 0
        )
        self.road.vehicles.append(self.vehicle)
        ...
```

Plus, I realized that state and action spaces are redefined every time `reset` is called, so I overrode `define_spaces` as well
```python
    @override(AbstractEnv)
    def define_spaces(self):
        super().define_spaces()
        self.action_space = spaces.Box(-1.0, 1.0, shape=(2,), dtype=np.float32)
```

Finally, I took your suggestion of checking if the vehicle went off-road and turned it into a terminating condition
```python
    @override(HighwayEnv)
    def _is_terminal(self):
        vehicle = self.vehicle
        return super()._is_terminal() or not vehicle.lane.on_lane(vehicle.position)
```

I still haven't run any algorithms on it but the basics seem to be working. It might need some fine tuning of the acceleration and steering coefficients. Plus, it seems that the ego vehicle doesn't always start aligned with the lane that it's in (i.e., it's not always parallel to the lanes).

Thanks a lot for the help!

**Comment by eleurent** [comment]
Hey Angelo, nice work! :+1: 

Instead of using your class `MyVehicle`, you could simply use the `Vehicle` class instead. `ControlledVehicle` and `MDPVehicle` are already a subclasses that add control logic over the low-level actions of `Vehicle`, so if you're going to bypass it you do not really need to inherit from these classes in the first place. I used directly the `Vehicle` class [here](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/parking_env.py#L92), for instance.

It is true that define_spaces must be overriden just like you did. In ParkingEnv, I actually [redefined](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/parking_env.py#L64) `reset()` to avoid this call to `define_spaces`, but your solution is much better. Will fix that.

> Plus, it seems that the ego vehicle doesn't always start aligned with the lane that it's in (i.e., it's not always parallel to the lanes).
That probably depends on the method you use to create the vehicle. If you use Vehicle.create_random() for instance, it should be aligned. If you create it manually, you should set manually heading to the lane heading at this position.

**Comment by angelolovatto** [comment]
Calling `Vehicle.create_random` totally works! This is what I'm doing now:
```python
    @override(HighwayEnv)
    def _create_vehicles(self):
        self.vehicle = Vehicle.create_random(self.road, 0)
        self.road.vehicles.append(self.vehicle)
        ...
```
I also had to update `_reward`, since `Vehicle` does not have some attributes that `MDPVehicle` has.
```python
    @override(HighwayEnv)
    def _reward(self, _):
        idx = self._curr_lane()
        action_reward = self.LANE_CHANGE_REWARD if idx != self._old_lane else 0
        self._old_lane = idx
        neighbours = self.road.network.all_side_lanes(self.vehicle.lane_index)
        state_reward = (
            +self.config["collision_reward"] * self.vehicle.crashed
            + self.RIGHT_LANE_REWARD
            * self.vehicle.lane_index[2]   # Changed from vehicle.target_lane_index
            / (len(neighbours) - 1)
            + self.HIGH_VELOCITY_REWARD
            * MDPVehicle.speed_to_index(self.vehicle.velocity)  # Changed from vehicle.velocity_index
            / (MDPVehicle.SPEED_COUNT - 1)
        )
        return utils.remap(
            action_reward + state_reward,
            [
                self.config["collision_reward"],
                self.HIGH_VELOCITY_REWARD + self.RIGHT_LANE_REWARD,
            ],
            [0, 1],
        )
```
Again, thanks a lot for your help!

**Comment by eleurent** [comment]
That looks great! I chose to use the target lane/velocity instead of the true state in the reward function so as to avoid skipping a reward because of a potential lag in the control response, but your changes make a lot of sense in the case of a Vehicle.
I'm closing this issue but please, definitely feel free to open another one if you have more questions!
ALSO: if you come up with a new interesting environment, please consider opening a pull request :)
Edouard
