### ISSUE TITLE
How to remove vehicles that arrive the end of road？

### ISSUE THREAD

**Issue by skonwa** [eleurent/highway-env#365]
Thanks for your great work.I got a question.I used multiagent merge environment and found that when vehicles arrived at the end of road they were still moving.In this case, rewards were still calculated,right?So,I want to remove the vehicles that have finished tasks,while ensuring that the network can learn properly.I don't know where to modify,and can you give me some suggestions?Thanks in advance.
![image](https://user-images.githubusercontent.com/92068333/192497541-9db1104c-9dd4-40d3-a034-e0ecc4a8ea69.png)

**Comment by eleurent** [comment]
Hi,
That is a good question, I'm not really sure how to handle this situation : the action and observation spaces have a fixed dimension, so if I remove a vehicle from the scene (when it leaves the scene) I'm not really sure what to do with the corresponding action (ignore it?) and observation (return a dummy observation? reuse the last observation continuously?)

**Comment by eleurent** [comment]
You may try to edit your multi-agent version of the merge environment as follows: when a controlled vehicle has finished,
- remove it from `env.road.vehicles`
- leave it in `env.controlled_vehicles`

This way, controlled vehicles that have finished:
- wont be simulated anymore
- wont be rendered
- won't cause collisions with other vehicles
- will still receive actions (but these will be ignored since the vehicles are not stepped)
- will still generate observations of their current state
- for the reward function, you can decided if you still want to count their contribution or not (by checking for each vehicle if it is still in the scene, i.e. in `env.road.vehicles`)

**Comment by skonwa** [comment]
@eleurent Thank you for your reply! That is good solution. In this way, the agents that have finished task will still get the actions and values from networks but we don't have to calculate the rewards for these agents to updata the networks parameters using their expriences, is that right? And idm vehicles can be removed directly from env.road.vehicles, right?

**Comment by eleurent** [comment]
> That is good solution. In this way, the agents that have finished task will still get the actions and values from networks but we don't have to calculate the rewards for these agents to updata the networks parameters using their expriences, is that right?

Yes I think it is better to remove the finished agents' contributions to the reward, otherwise e.g. if the last reward before termination was positive and we keep i, then the value function will treat the next timesteps as a sum of positive rewards, which is not really desired. So the reward of finished agents must be set to 0 instead (e.g. removed from the sum)

> And idm vehicles can be removed directly from env.road.vehicles; right?

Correct :)

**Comment by skonwa** [comment]
OK! I got it. Thank you for your patient answer.
