### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by amrzr** [eleurent/highway-env#385]
I am getting the following error intermittently during env.reset():

    245     else:
    246         obs = result
                 ...
--> 198             x = np.asarray(x, dtype=self.dtype)
    199 
    200         return bool(

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

I am using the latest development version.

**Comment by TongshenH** [comment]
I tried to change gym version==0.21.0, but it showed another error.

**Comment by eleurent** [comment]
Hi, 
I cannot reproduce the issue locally. This may be related to your agent code?
Please be mindful that since the gym 0.26 api change, `env.reset()` now returns a tuple `(obs, info)`

So if you have some code expects the old interface and does something like
```
obs = env.reset()
action = policy(obs)
```
then policy will receive a tuple instead of an array, and might complain.
