### ISSUE TITLE
A bug occurred during training.

### ISSUE THREAD

**Issue by GangHuiDong** [eleurent/highway-env#391]
https://user-images.githubusercontent.com/91947251/204080458-70826626-4f8e-4d27-a7aa-133316d2644d.mp4

Hello! I am a student studying reinforcement learning as your project.

While training in the highway-fast environment, the episode didn't end, so I tried to render it, and I could see that the above bug occurred.

What could be the problem?

**Comment by eleurent** [comment]
Hi,
This is because of a recent change I made: when reaching the maximum number of steps , the `truncation` is now raised rather than `termination/done` as before, following the new interface in gym >= 0.26.

This was done because a timeout should probably be considered differently as a collision, e.g. the value function should probably not be set to 0. 
But now that you mention this, I'm not so sure it makes sense anymore, the distinction between truncated and terminal is not so clear ^_^' Maybe we want actually want the timeout states to be terminal : if a reset is required, this is probably a good sign that the state is terminal.

Anyway, in the mean time you should simply interrupt simulation (and you can trigger an `env.reset`) based on the `truncated` signal only, instead of only done.
