### ISSUE TITLE
How add a new terminate funtion about vehicle lane off 

### ISSUE THREAD

**Issue by wuyukun-tong** [eleurent/highway-env#414]
Dear Prof.
 Following up the issue #310, I want to use the PPO algorithm to control both the steering wheel angle and acceleration of the vehicle in an intersection environment. I use the "kinematics"  observation type, it contains three off-lane parameters (long_off,lat_off,ang_off). I want to know why are these three parameters the offset of the ego-vehicle from the close lane and not the offset of its driving lane.
Additionally, I find it difficult to stay in the lane when controlling the steering wheel angle and acceleration at the same time, I would like to add a new function(off-line termination) to terminate the environment, for example when the vehicle deviates from the driving lane the environment will terminate. As the intersection environment includes both straight-ahead and left turns, how do I set the threshold when turning left? 
When the ego-vehicle is going straight we want it to stay in the lane and when turning we want it to successfully reach the target lane, so I don't quite understand how to set the threshold for the off-line termination.

**Comment by eleurent** [comment]
Hi,

> I want to know why are these three parameters the offset of the ego-vehicle from the close lane and not the offset of its driving lane.

Generally if a vehicle is driving on a given lane, then this should also be its closest lane. But I think you mean what happens when the vehicle start driving on another lane that its target? Then that's a good point, we could add similar features for its target lane rather than current lane. If you want to implement that, you can use something similar as:

https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/vehicle/kinematics.py#L195

and replace `self.lane` by `target_lane = self.road.network.get_lane(self.target_lane_index)`

> Additionally, I find it difficult to stay in the lane when controlling the steering wheel angle and acceleration at the same time, I would like to add a new function(off-line termination) to terminate the environment, for example when the vehicle deviates from the driving lane the environment will terminate. As the intersection environment includes both straight-ahead and left turns, how do I set the threshold when turning left?

Currently, there is an offroad termination condition that you can enable, which would end the episode whenever the vehicle drives off the road altogether. But it seems that you want to stop earlier, when the vehicle is too far from its target lane, which makes sense.
Then again, you would have to implement it in the env's is_terminated method:

https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/envs/intersection_env.py#L98

by adding the condition
```
target_lane = self.road.network.get_lane(self.vehicle.target_lane_index)
on_target_lane = target_lane.on_lane(self.vehicle.position)
```

> When the ego-vehicle is going straight we want it to stay in the lane and when turning we want it to successfully reach the target lane, so I don't quite understand how to set the threshold for the off-line termination.

I think at all time you can control the maximum lateral deviation from the target lane's centerline. This is what I am doing in the `on_lane` method mentioned above, but if you want implement your own criterion instead to better control the margins etc.

https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/road/lane.py#L80
