### ISSUE TITLE
Collision rewards cause skewd reward distribution 

### ISSUE THREAD

**Issue by Rosebash** [eleurent/highway-env#418]
Hello, there. Thanks for the great work!

The issue is that in default "highway-env" setting, collision_reward are relatively low(-1) in constrast to other rewards like highspeed_reward(+0.1), which would leads to the reward shift after lmap. So the reward recieved doesn't differ so much at every timestamp.

<img width="642" alt="image" style="zoom:20%;" src="https://user-images.githubusercontent.com/107114695/219921823-333dd532-0657-44bc-be7d-1f27b356f580.png">

This issue is likely to cause the adavantage function estimated bad in my experiements. Currently, I  compensate it by adding a epsilon survival reward each timestamp and zero out the collision reward. Would you consider adding this type of reward?

Your help is greatly appreciated.

**Comment by eleurent** [comment]
Hi, 
I'm not sure that I follow exactly what you are saying:
- indeed by default the collision reward is -1 and speed/right-lane rewards are in a range [0.-0.5].
- and indeed, a linear mapping is applied by default, which rescales the reward to the [0,1] range.
- but that means that already, if the vehicle is not in a collision state, the reward=0 it receives is converted to reward = 0.66, which you can already see as a survival reward (as opposed to collisions giving a terminal r=0 reward).

Anyway, this should all be configurable directly: you can disable `normalize_reward` if you don't like it, and you can set the collision_reward etc. directly to whichever value you like.

Let me know if I am missing something or you have any question.

**Comment by Rosebash** [comment]
Thanks a lot,

But I'm wondering if you notice that the rewards are almost always greater than 0.66. And a tiny speed/right reward would make the l-mapped reward near 1, which in turn makes ALL_ACTIONS being rewarded roughly same value. 

Under RL, the ego vehicle's best solution is to slow down and follow the front car. 

I don't know if it was clarified a bit more, but I will upload some experiment result in the future.

**Comment by eleurent** [comment]
If I understand correctly, you are saying that 
- the +1 reward for avoiding collisions is significantly larger than other reward terms -speed and right lane, which can only total at +0.5
- thus, a "bad" conservative policy which stays safe by driving slowly has a value of 1*H, is already near-optimal (1*T is 66% of the optimal value of 1.5*T, where T is episode length), and there isnt much incentive for the agent to discover something better

(I ignored the reward normalisation here, since it does not affect the ranking of policies)

I guess you are right that 2/3 of the optimising effort is allocated on just "staying alive", but there is still 1/3 on efficiency which is not negligible, and in my experience RL agents have been able to take advantage this 1/3 signal.

But of course these weights are all configurable, so feel free to adjust them if you think a different weighting of safety vs efficiency is preferable :)
