### ISSUE TITLE
issue about POMDP

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#419]
Hello, how can I change the environment MDP to POMDP? Is there an implementation in the code?
Thanks~

**Comment by eleurent** [comment]
Hi, 
I would say the environment is already a POMDP, since the agent typically only accesses *observations* which only partially describe the scene, it does not observe the full simulator state (which would include hidden variables like the destinations of other vehicles, their driving style parameters, etc.)

**Comment by eleurent** [comment]
If you mean a POMDP in the sense that the agent would be provided with the observation function, which maps the full simulator state to observations (so it can perform bayesian inference about the true simulator state for instance), then no, there is no implementation in the code which is dedicated specifically to solving POMDPs exactly.

But if you need them, these observation functions are available here:
https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py
(there are several of them because we can configure several types of observations).
