### ISSUE TITLE
observation about intersection-multi-agent-v0

### ISSUE THREAD

**Issue by SEUCGX** [eleurent/highway-env#427]
Thank you for your excellent environment. I can't understand how its coordinates and speed are defined in this scene. I can't seem to find the relevant documentation. In addition, it seems that I can't get satisfactory results with your configuration as follows.
python experiments.py evaluate configs/IntersectionEnv/env_multi_agent.json \
                               configs/IntersectionEnv/agents/DQNAgent/ego_attention_2h.json \
                               --train --episodes=3000
To be precise, I got the result that one car would always stay in place.
Is it because of the update of the version?
According to my understanding of this code, I think you want all agents to use the same network and the same reward value for training. This setting makes me confused, which means that the training environment is unstable. Am I wrong？

**Comment by eleurent** [comment]
>I can't understand how its coordinates and speed are defined in this scene. I can't seem to find the relevant documentation.

See the [documentation](https://highway-env.readthedocs.io/en/latest/observations/index.html).

>  In addition, it seems that I can't get satisfactory results with your configuration as follows.
python experiments.py evaluate configs/IntersectionEnv/env_multi_agent.json
configs/IntersectionEnv/agents/DQNAgent/ego_attention_2h.json
--train --episodes=3000.  To be precise, I got the result that one car would always stay in place.

I got okay results when I tried it, which was a long time ago. But this project is mostly about defining the environment, not the agent. Feel free to experiment more, and try other algorithms / observations types / network architectures.

> According to my understanding of this code, I think you want all agents to use the same network and the same reward value for training. This setting makes me confused, which means that the training environment is unstable. Am I wrong？

Yes, it is a cooperative setting where all agents are controlled by the same policy, and they all optimise the same joint reward function. I don't think there is anything particularly wrong with this setting, although others are definitely possible, again feel free to experiment. This is just a simple implementation of a multi-agent task.

**Comment by SEUCGX** [comment]
I have noticed that you only add the results of each agent's interaction with the environment to the buffer in your code, which means that the environment is unstable for each agent. 
This is similar to but somewhat different from vdn. Although each agent uses the same policy network, in the construction of the loss function, in fact, each local q value is added up to approximate the total q value.  Joint rewards are also used in loss. However, in your settings, loss seems to be the q value for each agent, which seems to mean that multiple agents only increase the number of samples taken.  If each agent trains separately, the reward value should be obtained by each agent itself.  Therefore, it is difficult for me to understand your current thinking when constructing the loss function. Can you show more detail?

**Comment by SEUCGX** [comment]
> 
You have provided an explanation document for the environment, which mainly introduces the coordinate meaning of highway v0, which is indeed easy to understand. But when the environment becomes a intersection, the meaning of speed and location x and y begins to become confusing. Is there a separate document?

**Comment by eleurent** [comment]
> You have provided an explanation document for the environment, which mainly introduces the coordinate meaning of highway v0, which is indeed easy to understand. But when the environment becomes a intersection, the meaning of speed and location x and y begins to become confusing. Is there a separate document?

The meaning is the same for the intersection environment: vehicles also have an x/y coordinate and a vx/vy velocity. Different options can be used, e.g. absolute coordinates are used by default for intersection env, while relative coordinates are used for highway. I invite you to take a look at the KinematicsObservation class, and the environment configuration.

> I have noticed that you only add the results of each agent's interaction with the environment to the buffer in your code, which means that the environment is unstable for each agent.
This is similar to but somewhat different from vdn. Although each agent uses the same policy network, in the construction of the loss function, in fact, each local q value is added up to approximate the total q value. Joint rewards are also used in loss. However, in your settings, loss seems to be the q value for each agent, which seems to mean that multiple agents only increase the number of samples taken. If each agent trains separately, the reward value should be obtained by each agent itself. Therefore, it is difficult for me to understand your current thinking when constructing the loss function. Can you show more detail?

You are right that each agent could optimise its own per-agent reward, but here I chose another option: each agent receives an "altruistic reward", which is the sum of the per-agent rewards. Thus, each agent optimises not only its own velocity and safety, but also acts in an altruistic manner so as to also increase other agents' safety and speed (e.g. dont cut in before other agents, make them brake too hard, etc.). You can also see it as a specific case of the per-agent rewards, where they are all equal (to a sum of several terms), there is nothing wrong with that. And we can train Q-values for this (joint) reward function as you would for a single-player RL algorithm that assumes that other agents have fixed policies (local approximation).

Again, if this setting is not suitable for you, feel free to change it :) I don't have particularly strong opinions about this, I mostly made this choice so that the environment returns a scalar reward (the same for all agents) instead of a vector reward (different for each agent), so that it can be used directly with single-player RL algorithms and libraries (which expect scalar rewards).

**Comment by SEUCGX** [comment]
> You are right that each agent could optimise its own per-agent reward, but here I chose another option: each agent receives an "altruistic reward", which is the sum of the per-agent rewards. Thus, each agent optimises not only its own velocity and safety, but also acts in an altruistic manner so as to also increase other agents' safety and speed (e.g. dont cut in before other agents, make them brake too hard, etc.). You can also see it as a specific case of the per-agent rewards, where they are all equal (to a sum of several terms), there is nothing wrong with that. And we can train Q-values for this (joint) reward function as you would for a single-player RL algorithm that assumes that other agents have fixed policies (local approximation).
Again, if this setting is not suitable for you, feel free to change it :) I don't have particularly strong opinions about this, I mostly made this choice so that the environment returns a scalar reward (the same for all agents) instead of a vector reward (different for each agent), so that it can be used directly with single-player RL algorithms and libraries (which expect scalar rewards).
I see. Thank you very much for your help. I am learning the reward value settings for multi-agent systems, and your explanation has provided great help.

**Comment by SEUCGX** [comment]
> The meaning is the same for the intersection environment: vehicles also have an x/y coordinate and a vx/vy velocity. Different options can be used, e.g. absolute coordinates are used by default for intersection env, while relative coordinates are used for highway. I invite you to take a look at the KinematicsObservation class, and the environment configuration.

I seem to understand. In fact, there are positive and negative speeds for cars on the east-west direction because some cars move from west to east （positive) and some cars move from east to west (negative).
