### ISSUE TITLE
Preventing vehicle from going off-road?

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#67]
I think having a signal indicating the vehicle has gone off the road is useful, and one can terminate the episode with the use of this and shorten the training time for continuous action environments.

Of course, an alternative is to use a time step limit, but even with that limit put on, you can have a much more informative episode on the road, rather than off-road, in limited time steps.

**Comment by eleurent** [comment]
Good idea. It can easily be added to the vehicle properties:
```
@property
def on_road(self):
    return self.lane.on_lane(self.position)
```
The question of the actual environment observation remains. The `AttributeObservation` can be used to return a dict `{"on_road": env.vehicle.on_road}`, but it will not be sufficient and must probably included in a Tuple observation, that will depend on the actual environment specification.

**Comment by eleurent** [comment]
Also mentionned in #66: the lane coordinates (longitudinal, lateral) could be added to possible features of the KinematicsObservation, and could serve as a proxy for offroad detection (lateral > lane.width)

**Comment by mhtb32** [comment]
> The question of the actual environment observation remains. The `AttributeObservation` can be used to return a dict `{"on_road": env.vehicle.on_road}`, but it will not be sufficient and must probably included in a Tuple observation, that will depend on the actual environment specification.

What's the purpose of adding it to observations? Do you mean for situations that you don't want to terminate the episode while going off-road?

**Comment by mhtb32** [comment]
> Good idea. It can easily be added to the vehicle properties:
> 
> ```
> @property
> def on_road(self):
>     return self.lane.on_lane(self.position)
> ```

So, if you think this might benefit users generally, please push the changes. Notify me otherwise.

**Comment by eleurent** [comment]
> > The question of the actual environment observation remains. The `AttributeObservation` can be used to return a dict `{"on_road": env.vehicle.on_road}`, but it will not be sufficient and must probably included in a Tuple observation, that will depend on the actual environment specification.
> 
> What's the purpose of adding it to observations? Do you mean for situations that you don't want to terminate the episode while going off-road?

Yes, that is what I meant. Of course, episode termination is a simpler and sound approach, so it's a good first step.

> So, if you think this might benefit users generally, please push the changes. Notify me otherwise.

I do, and I will.

**Comment by mhtb32** [comment]
Thank you :pray:

**Comment by Exasor** [comment]
> Yes, that is what I meant. Of course, episode termination is a simpler and sound approach, so it's a good first step.

I wonder whether the agent can learn to prevent going off-road by just terminating the episode while off-road, because while using `KinematicObservation` , the observation only describes the relationship between ego vehicle and other vehicles, lacking the information such as the distance from vehicle to road boundary or the `on_road` property

**Comment by eleurent** [comment]
You are right, the agent must be able to predict from its observation that it is going off-road, and it won’t be the case in general with any observation type. 

One particular case is the KinematicsObservation on a scene with a straight horizontal road, since the [0, ‘y’] entry gives the lateral position of the ego vehicle on the road (<0 or >1 is offroad)

Another possibility is to use the image observation, which shows both the ego vehicle and the roads.

**Comment by Exasor** [comment]
What is [0, 'y'] entry mean? I have a question that in `StraightLane(AbstractLane)` , does the `lateral` value from `local_coordinates` describe the lateral position between vehicle and the center of lane? for in `on_lane` method, if `np.abs(lateral) <= self.width_at(longitudinal) / 2 + margin` , this vehicle is on lane, and `self.width_at(longitudinal) / 2` is the distance from the center of lane to the lane boundary, so I think `lateral` value can be appended after the `KinematicObservation` is reshaped into a (1, ) list and put them into network together, while np.abs(lateral) > self.width_at(longitudinal) / 2, it implies that vehicle is off-road

**Comment by eleurent** [comment]
> What is [0, 'y'] entry mean? 

the kinematic observation is a 2D arrays, the rows refer two vehicles (0 is ego-vehicle), and the columns refer to coordinates such as x, y, v_x, v_y etc. 'y' coordinate is typically the second entry, so i meant observation[0, 1] is the y position of the ego-vehicle.

> does the lateral value from local_coordinates describe the lateral position between vehicle and the center of lane? 

Yes

>  so I think lateral value can be appended after the KinematicObservation is reshaped into a (1, ) list and put them into network together, while np.abs(lateral) > self.width_at(longitudinal) / 2, it implies that vehicle is off-road

Sure, that is possible. To make it more generic, and in the spirit of the KinematicObservation, it would be better to add a "lateral" feature for each vehicle, so that it can be made a new column of the Kinematic Observation (rather than reshaping the 2D array).
And if you only want the ego-vehicle's lateral position, I suggest that you create a new ObservationType to include whichever information you deem useful.

**Comment by Exasor** [comment]
Thanks a lot for your suggestion! For the range of observation, I find in `normalize_obs` method of `KinematicObservation`, the feature ranges of x, y are
```
"x": [-5.0 * MDPVehicle.SPEED_MAX, 5.0 * MDPVehicle.SPEED_MAX],
"y": [-AbstractLane.DEFAULT_WIDTH * len(side_lanes), AbstractLane.DEFAULT_WIDTH * len(side_lanes)]
```
while `MDPVehicle.SPEED_MAX` = 30, it seems that after running for several seconds(over 5*30m), the normalized x value will keep in 1, making normalization meaningless. As for the range of y, in highway env, the origin location of the center of first lane is (0,0), so I think `[-AbstractLane.DEFAULT_WIDTH/2, AbstractLane.DEFAULT_WIDTH*lanes_count-AbstractLane.DEFAULT_WIDTH/2]` is more proper.

**Comment by eleurent** [comment]
Right, it is because these values where chosen to scale the x/y coordinates of other vehicles *relative to the ego-vehicle*, rather than that of the ego-vehicle, so the x range is +/- 5 seconds at full speed, and y range is +/- the width of the road.
But it can be change to suit your needs.

**Comment by Exasor** [comment]
oh I got it, I made the order of `absolute` and `normalize` for mistake. Thank you very much!
