### ISSUE TITLE
Question about grid observation type

### ISSUE THREAD

**Issue by jkewang** [eleurent/highway-env#74]
Hi @eleurent , I'm using intersection env with "OccupancyGrid" as observation type. I set it with following code:
`observation = {
            "type": "OccupancyGrid",
            "vehicles_count": 15,
            "features": ['presence', 'vx', 'vy'],
            "features_range": {
                "x": [-100, 100],
                "y": [-100, 100],
                "vx": [-20, 20],
                "vy": [-20, 20]
            },
            "grid_size": [[-30, 30], [-30, 30]],
            "grid_step": [5, 5],
            "absolute": False
        }`
It really outputs a three dimension grid map, I think the 'vx' and 'vy' are normalized and remap to the x-y coordinate system as last two outputs. But I just can't understand what's the meaning of the first output "presence" in this case? Or do I misunderstand the use of this API?

**Comment by eleurent** [comment]
Hi @jkewang, 
As you said, the width and height of the grid represent the x-y coordinates system around the vehicle., and the channels 1 and 2 represent the relative (normalized) velocity (vx, vy) of nearby vehicles.
But then, a vehicle driving at the same speed as the ego-vehicle will have a value of 0 in these channels. In order to be able to distinguish this situation from the mere absence of vehicle, a _presence_ channel is added (channel 0) which takes the value 1 wherever there is a vehicle, 0 else.
Does that make sense to you?

**Comment by jkewang** [comment]
Thanks for your reply! It's a clever design!
