### ISSUE TITLE
Question - About reward mapping in HighwayEnv

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#78]
Hi Edouard!

Can you explain more about the `utils.remap()` function? in HighwayEnv's reward method, It seems that it is mapping reward to a line segment. Why is it necessary?

**Comment by mhtb32** [comment]
I think this is answered in #41, sorry for the duplication.

**Comment by mhtb32** [comment]
Although I suggest refactoring the function like this:

```Python
def lmap(v: float, x: Interval, y: Interval) -> float:
    """Maps value v with range x to desired range y"""
    return y[0] + (v-x[0])*(y[1]-y[0])/(x[1]-x[0])
```

**Comment by eleurent** [comment]
I would like to add that the assumption that rewards are bounded is not only practical for deep rl purpose, it is also required in the theory of the exploration-exploitation dilemma (it is exploited in monte-carlo tree search algorithms, for instance). And then, using the range [0, 1] instead of [R_min, R_max] is just a convention.
