### ISSUE TITLE
Question on IDM usage as ego policy

### ISSUE THREAD

**Issue by AkshayNemade** [eleurent/highway-env#84]
Hi :) ,

Can the ego vehicle be IDMvehcile? This feature would be usefull if the neighbouring vehicles are provided with real tracks from a dataset and  IDM is used maneuver amongst them.

Currently simply changing the self.vehicle = IDMVehicle() in abstract env doesn't work as it gives the error
AttributeError: 'IDMVehicle' object has no attribute 'SPEED_COUNT'

Any work around this?

**Comment by eleurent** [comment]
Hi @AkshayNemade
IDM is a longitudinal model, responsible for adjusting the vehicle velocity.
You could use it for the ego-vehicle, but then what would be the action space? Only lateral actions (lane change decisions or steering control), maybe?

For now, only two action spaces have been considered:
* a Discrete space, with 5 actions: IDLE, FASTER, SLOWER, LANE-RIGHT and LANE-LEFT.
* a Continuous space with 2 actions: throttle and steering

Thus, you get this error because the current Discrete action space requires being able to handle the FASTER/SLOWER actions, which involves a finite set of target speeds. These are not defined for IDM (which adjusts its acceleration continuously), so a work around would be to define a new action space with only lateral controls.

**Comment by AkshayNemade** [comment]
I am sorry for being not clear. I meant both IDM and MOBIL.. which IDM vehicle object use.
I see that the continuous actions are also passed in the env. So cant IDM+MOBIL, accelerations + steering controls passed internally?

**Comment by eleurent** [comment]
So you want the ego-vehicle to behave according to IDM+MOBIL, as for any other vehicle.
It is of course possible, but that would make highway-env a simulator, rather than a reinforcement learning environment: you cannot provide actions to control the simulation, which runs on its own.

You can achieve this by simply commenting the `vehicle.act(action)` line in `AbstractEnv`. This means that the action will be ignored when calling `env.step(action)`
